// eslint-disable-next-line import/prefer-default-export
export const insightDimensions = [
  {
    groupId: 'normal',
    groupName: '常用维度',
    id: 'd',
    name: '域名',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'user',
    groupName: '用户属性',
    id: 'usr_t_date_1',
    name: '测试日期型',
    type: 'usr',
    valueType: 'date',
  },
  {
    groupId: 'user',
    groupName: '用户属性',
    id: 'usr_t_number_1',
    name: '测试数值型',
    type: 'usr',
    valueType: 'int',
  },
  {
    groupId: 'user',
    groupName: '用户属性',
    id: 'usr_sex002',
    name: 'sex002',
    type: 'usr',
    valueType: 'string',
  },
  {
    groupId: 'origin',
    groupName: '用户来源',
    id: 'rd',
    name: '访问来源',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'origin',
    groupName: '用户来源',
    id: 'rt',
    name: '一级访问来源',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'origin',
    groupName: '用户来源',
    id: 'kw',
    name: '搜索词',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'origin',
    groupName: '用户来源',
    id: 'utm_source',
    name: '广告来源',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'origin',
    groupName: '用户来源',
    id: 'utm_campaign',
    name: '广告名称',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'origin',
    groupName: '用户来源',
    id: 'utm_content',
    name: '广告内容',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'origin',
    groupName: '用户来源',
    id: 'utm_term',
    name: '广告关键字',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'origin',
    groupName: '用户来源',
    id: 'utm_medium',
    name: '广告媒介',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'origin',
    groupName: '用户来源',
    id: 'ch',
    name: '自定义App渠道',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'geo',
    groupName: '地域信息',
    id: 'city',
    name: '城市',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'geo',
    groupName: '地域信息',
    id: 'region',
    name: '地区',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'geo',
    groupName: '地域信息',
    id: 'countryCode',
    name: '国家代码',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'geo',
    groupName: '地域信息',
    id: 'countryName',
    name: '国家名称',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'device',
    groupName: '设备信息',
    id: 'bw',
    name: '浏览器',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'device',
    groupName: '设备信息',
    id: 'bwv',
    name: '浏览器版本',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'device',
    groupName: '设备信息',
    id: 'os',
    name: '操作系统',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'device',
    groupName: '设备信息',
    id: 'osv',
    name: '操作系统版本',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'device',
    groupName: '设备信息',
    id: 'shw',
    name: '屏幕大小（高*宽）',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'device',
    groupName: '设备信息',
    id: 'l',
    name: '操作系统语言',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'device',
    groupName: '设备信息',
    id: 'db',
    name: '设备品牌',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'device',
    groupName: '设备信息',
    id: 'dm',
    name: '设备型号',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'device',
    groupName: '设备信息',
    id: 'o',
    name: '设备方向',
    type: 'global',
    valueType: null,
  },
  {
    id: 'AbQ3bDYe',
    isPrimaryKey: false,
    key: 'order_name',
    type: 'itm',
    groupId: 'item',
    name: 'shangpin',
    groupName: '物品属性',
    valueType: 'string',
    description: '',
    associatedId: 'var_engageType',
  },
  {
    associatedId: '',
    groupId: 'event',
    groupName: '事件变量',
    id: 'var_engageType',
    name: '产品交互性参与类型',
    type: 'event',
    valueType: 'string',
  },
  {
    groupId: 'normal',
    groupName: '常用维度',
    id: 'tm',
    name: '时间我是超级长的名字超级长的名字超级长的名字超级长的名字超级长的名字超级长的名字超级长的名字超级长的名字超级长的名字超级长的名字超级长的名字超级长的名字超级长的名字超级长的名字',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'normal',
    groupName: '常用维度',
    id: 'b',
    name: '应用平台',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'normal',
    groupName: '常用维度',
    id: 'cv',
    name: '应用版本',
    type: 'global',
    valueType: null,
  },
];
