/* eslint-disable import/prefer-default-export */
export const allVariables = {
  eventVariables: [
    {
      key: 'float_111',
      id: 'AbQ3bDYe',
      description: '测试小数事件属性',
      creatorId: 'rRGoYQml',
      creator: 'haozhigang',
      createdAt: '2020-12-21T07:27:53.850813Z',
      name: '小数111',
      updater: null,
      updaterId: '',
      valueType: 'double',
      updatedAt: '2020-12-21T07:27:53.851123Z',
    },
    {
      key: 'r',
      id: 'y9pm1pme',
      description: '',
      creatorId: 'nxGK0Da6',
      creator: 'mayutong',
      createdAt: '2020-12-15T08:17:46.658697Z',
      name: '范若若f',
      updater: null,
      updaterId: '',
      valueType: 'string',
      updatedAt: '2020-12-15T08:17:46.665649Z',
    },
    {
      key: 'ok',
      id: 'WlGk4Daj',
      description: '',
      creatorId: 'n1QVaDyR',
      creator: 'lvyuqiang',
      createdAt: '2020-12-14T05:43:35.127775Z',
      name: 'ok',
      updater: null,
      updaterId: '',
      valueType: 'string',
      updatedAt: '2020-12-14T05:43:35.130736Z',
    },
  ],
  userVariables: [
    {
      createdAt: '2020-12-21T07:11:55.125365Z',
      description: '',
      id: 'AbQ3bDYe',
      key: 't_date_1',
      name: '测试日期型',
      updatedAt: '2020-12-21T07:11:55.125461Z',
      updater: null,
      updaterId: '',
      valueType: 'date',
    },
    {
      createdAt: '2020-12-21T07:11:23.924133Z',
      description: '',
      id: 'y9pm1pme',
      key: 't_number_1',
      name: '测试数值型',
      updatedAt: '2020-12-21T07:11:23.924161Z',
      updater: null,
      updaterId: '',
      valueType: 'int',
    },
    {
      createdAt: '2020-12-14T05:44:03.339789Z',
      description: '',
      id: 'WlGk4Daj',
      key: 'sex002',
      name: 'sex002',
      updatedAt: '2020-12-14T05:44:03.342662Z',
      updater: null,
      updaterId: '',
      valueType: 'string',
    },
  ],
  tags: [
    {
      key: '1',
      detector: {
        description: null,
        detectedAt: '2020-12-21T16:14:40.958Z',
        totalUsers: 0,
        usersRatio: 0,
      },
      name: '8888',
      type: 'AGGREGATED',
      valueType: {
        type: 'INT',
      },
    },
  ],
  preparedDimensions: [
    {
      description: '事件发生的时间（日期）',
      example: '2019-01-01',
      id: 'tm',
      name: '时间',
      platforms: ['all'],
    },
    {
      description:
        'Web 端理解为： "www.example.com" 是 https://www.example.com/about 的域名。APP 理解为应用的包名。小程序理解为 AppID',
      example: 'www.example.com',
      id: 'd',
      name: '域名',
      platforms: ['all'],
    },
    {
      description:
        'Web 端理解为： "/about" 是https://www.example.com/about的页面。Android 应用理解为: activity + fragment。iOS 应用理解为：UIViewController。小程序理解为：页面 URL（不包括 query ）',
      example: 'https://www.example.com/circle',
      id: 'p',
      name: '页面',
      platforms: ['all'],
    },
    {
      description: '访问页面的上级页面来源',
      example: '/circle',
      id: 'rp',
      name: '页面来源',
      platforms: ['all'],
    },
    {
      description: '应用所属平台，包括：Web、iOS、Android、微信小程序、支付宝小程序、微信公众号等',
      example: 'Web、iOS、Android、MinP',
      id: 'b',
      name: '应用平台',
      platforms: ['all'],
    },
    {
      description: 'App 和小程序的版本号',
      example: '5.1、5.2',
      id: 'cv',
      name: 'App 版本',
      platforms: ['iOS', 'Android', 'minp', 'wxwv', 'minigame', 'alip'],
    },
    {
      description: '圈选某个元素时，如果该元素本身有 "内容"信息，即可用 "元素内容" 来统计该元素对应的指标',
      example: '立即注册、立即购买',
      id: 'v',
      name: '元素内容',
      platforms: ['all'],
    },
    {
      description: '圈选某个元素时，如果该元素本身有 "位置"信息，即可用 "元素位置"来统计该元素对应的指标',
      example: '1、2、3',
      id: 'idx',
      name: '元素位置',
      platforms: ['all'],
    },
    {
      description:
        '网站的流量来源，可以是百度，谷歌，优酷等站外渠道，也可能是直接访问该网站。可以通过设置 UTM 参数来确定流量具体是哪个广告带来的',
      example: 'www.baidu.com、m.baidu.com、直接访问、微信-其他',
      id: 'rd',
      name: '访问来源',
      platforms: ['all'],
    },
    {
      description:
        '为了便于分析，我们将访问来源进行了归类。分为直接访问，搜索引擎，社交媒体，外部链接四大部分。直接访问： 可能是用户直接在浏览器中输入了一个域名或使用书签进行访问；搜索引擎： www.baidu.com，m.baidu.com，so.com，sogou.com 等；社交媒体：weibo.com，zhihu.com，linkedin.com， facebook.com，mp.weixin.qq.com 等；外部链接： 除了社交媒体，搜索⽹站之外的来源',
      example: '直接访问、搜索引擎、社交媒体、外部链接',
      id: 'rt',
      name: '一级访问来源',
      platforms: ['all'],
    },
    {
      description:
        '用户从搜索引擎进入网站所使用的搜索词，一般情况下付费搜索的搜索词可以被解析，但由于谷歌、百度、搜狗等搜索引擎对自然搜索搜索词加密的原因，来自这些搜索引擎的自然搜索搜索词将以“（xx自然流量）”的形式展示。如果在值中出现 N/A ，意为这部分流量不是通过搜索词访问的',
      example: '热力图、(百度自然流量)、(搜狗自然流量)',
      id: 'kw',
      name: '搜索词',
      platforms: ['web', 'wxwv'],
    },
    {
      description: 'utm_source，标识投放的广告来源，例如：google、baidu、toutiao',
      example: 'google、baidu、toutiao',
      id: 'utm_source',
      name: '广告来源',
      platforms: ['all'],
    },
    {
      description: 'utm_campaign，标识投放产品的具体广告系列名称、标语、促销代码等',
      example: 'springsale',
      id: 'utm_campaign',
      name: '广告名称',
      platforms: ['all'],
    },
    {
      description:
        'utm_content，用于区分相似内容或同一广告内的链接。如果在同一封 EDM 中使用了两个不同的链接，就可以使用 utm_content 设置不同的值，以便判断哪个版本的效果更好',
      example: 'textlink',
      id: 'utm_content',
      name: '广告内容',
      platforms: ['all'],
    },
    {
      description: 'utm_term，标识投放的付费搜索关键字',
      example: 'running+shoes',
      id: 'utm_term',
      name: '广告关键字',
      platforms: ['all'],
    },
    {
      description: 'utm_medium，标识投放的广告媒介或营销媒介，例如：CPC、Banner 和 Edm',
      example: 'cpc、banner、EDM',
      id: 'utm_medium',
      name: '广告媒介',
      platforms: ['all'],
    },
    {
      description:
        '自定义 App 渠道。在 App 集成 SDK 的时候，针对安卓用户，设置分包渠道。在小程序中，则自动获取小程序打开的来源。目前支持微信中 60 多种统计场景',
      example: 'huawei、oppo、vivo、xiaomi',
      id: 'ch',
      name: '自定义 App 渠道',
      platforms: ['iOS', 'Android', 'minp', 'alip', 'minigame', 'baidup', 'qq', 'bytedance'],
    },
    {
      description:
        '用户访问时所在的城市，Web 基于 IP 地址， App 和小程序 基于 IP 地址和 GPS 。优先判断 GPS 值，GPS 值缺失时，使用 IP 地址',
      example: '北京、上海、深圳、天津',
      id: 'city',
      name: '城市',
      platforms: ['all'],
    },
    {
      description:
        '用户访问时所在的地区，Web 基于IP地址，该维度包含国内省级以上行政区，以及国外地区。 App 和小程序 基于 IP 地址和 GPS 。优先判断 GPS 值，GPS 值缺失时，使用IP地址',
      example: '北京、上海、广东、浙江',
      id: 'region',
      name: '地区',
      platforms: ['all'],
    },
    {
      description: '⽤户所在的国家的英⽂缩写',
      example: 'CN，US，JP，SG',
      id: 'countryCode',
      name: '国家代码',
      platforms: ['all'],
    },
    {
      description: '⽤户所在的国家的名称',
      example: '中国，美国，英国，新加坡',
      id: 'countryName',
      name: '国家名称',
      platforms: ['all'],
    },
    {
      description: '⽤户所⽤浏览器的类型',
      example: 'Chrome，Chrome Mobile， Safari，IE',
      id: 'bw',
      name: '浏览器',
      platforms: ['web', 'wxwv'],
    },
    {
      description: '同「浏览器」，但是会按照不同的版本进⾏区分',
      example: 'Chrome 47.0.2526 、IE 8.0、Firefox 65.0',
      id: 'bwv',
      name: '浏览器版本',
      platforms: ['web', 'wxwv'],
    },
    {
      description: '用户所使用的操作系统',
      example: 'Mac OS X ，Android，weixin-iOS，weixin-Android',
      id: 'os',
      name: '操作系统',
      platforms: ['all'],
    },
    {
      description: '同「操作系统」，但是会按照不同的版本进⾏区分',
      example: 'Android 4.0、Windows 8 ，Windows 7 ',
      id: 'osv',
      name: '操作系统版本',
      platforms: ['all'],
    },
    {
      description: 'Web 端是窗⼝⼤⼩，移动端是屏幕⼤⼩',
      example: '640*360、1920*1080',
      id: 'shw',
      name: '屏幕大小（高*宽）',
      platforms: ['all'],
    },
    {
      description: '统计不同的操作系统语⾔的使⽤情况',
      example: '简体中⽂、英语、繁体中文',
      id: 'l',
      name: '操作系统语言',
      platforms: ['all'],
    },
    {
      description: '设备的品牌',
      example: 'Apple、xiaomi、huawei、oppo',
      id: 'db',
      name: '设备品牌',
      platforms: ['all'],
    },
    {
      description: '设备具体的机型',
      example: 'iPhone X、iPhone 8 Plus、OPPO R11',
      id: 'dm',
      name: '设备型号',
      platforms: ['all'],
    },
    {
      description: '用户访问时使用的设备方向',
      example: '竖直、横向',
      id: 'o',
      name: '设备方向',
      platforms: ['iOS', 'Android'],
    },
  ],
  itemVariables: [
    {
      id: 'AbQ3bDYe',
      isPrimaryKey: false,
      key: 'order_name',
      name: 'shangpin',
      updatedAt: '2020-12-22T02:45:11.309583Z',
      valueType: 'string',
      description: '',
    },
    {
      id: 'y9pm1pme',
      isPrimaryKey: true,
      key: 'wp_1',
      name: '物品属性1',
      updatedAt: '2020-12-21T07:48:10.059456Z',
      valueType: 'string',
      description: '物品属性1',
    },
    {
      id: 'WlGk4Daj',
      isPrimaryKey: true,
      key: 'order_id',
      name: 'order_id',
      updatedAt: '2020-12-14T05:44:42.765921Z',
      valueType: 'string',
      description: '',
    },
  ],
};

export const insightDimensions = [
  {
    groupId: 'normal',
    groupName: '常用维度',
    id: 'tm',
    name: '时间',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'normal',
    groupName: '常用维度',
    id: 'd',
    name: '域名',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'normal',
    groupName: '常用维度',
    id: 'b',
    name: '应用平台',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'normal',
    groupName: '常用维度',
    id: 'cv',
    name: 'App 版本',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'user',
    groupName: '用户属性',
    id: 'usr_t_date_1',
    name: '测试日期型',
    type: 'usr',
    valueType: 'date',
  },
  {
    groupId: 'user',
    groupName: '用户属性',
    id: 'usr_t_number_1',
    name: '测试数值型',
    type: 'usr',
    valueType: 'int',
  },
  {
    groupId: 'user',
    groupName: '用户属性',
    id: 'usr_sex002',
    name: 'sex002',
    type: 'usr',
    valueType: 'string',
  },
  {
    groupId: 'origin',
    groupName: '用户来源',
    id: 'rd',
    name: '访问来源',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'origin',
    groupName: '用户来源',
    id: 'rt',
    name: '一级访问来源',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'origin',
    groupName: '用户来源',
    id: 'kw',
    name: '搜索词',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'origin',
    groupName: '用户来源',
    id: 'utm_source',
    name: '广告来源',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'origin',
    groupName: '用户来源',
    id: 'utm_campaign',
    name: '广告名称',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'origin',
    groupName: '用户来源',
    id: 'utm_content',
    name: '广告内容',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'origin',
    groupName: '用户来源',
    id: 'utm_term',
    name: '广告关键字',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'origin',
    groupName: '用户来源',
    id: 'utm_medium',
    name: '广告媒介',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'origin',
    groupName: '用户来源',
    id: 'ch',
    name: '自定义 App 渠道',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'geo',
    groupName: '地域信息',
    id: 'city',
    name: '城市',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'geo',
    groupName: '地域信息',
    id: 'region',
    name: '地区',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'geo',
    groupName: '地域信息',
    id: 'countryCode',
    name: '国家代码',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'geo',
    groupName: '地域信息',
    id: 'countryName',
    name: '国家名称',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'device',
    groupName: '设备信息',
    id: 'bw',
    name: '浏览器',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'device',
    groupName: '设备信息',
    id: 'bwv',
    name: '浏览器版本',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'device',
    groupName: '设备信息',
    id: 'os',
    name: '操作系统',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'device',
    groupName: '设备信息',
    id: 'osv',
    name: '操作系统版本',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'device',
    groupName: '设备信息',
    id: 'shw',
    name: '屏幕大小（高*宽）',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'device',
    groupName: '设备信息',
    id: 'l',
    name: '操作系统语言',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'device',
    groupName: '设备信息',
    id: 'db',
    name: '设备品牌',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'device',
    groupName: '设备信息',
    id: 'dm',
    name: '设备型号',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'device',
    groupName: '设备信息',
    id: 'o',
    name: '设备方向',
    type: 'global',
    valueType: null,
  },
  {
    id: 'AbQ3bDYe',
    isPrimaryKey: false,
    key: 'order_name',
    type: 'itm',
    groupId: 'item',
    name: 'shangpin',
    groupName: '物品属性',
    valueType: 'string',
    description: '',
  },
];
