// eslint-disable-next-line import/prefer-default-export
export const insightDimensions = [
  {
    groupId: 'normal',
    groupName: '常用维度',
    id: 'd',
    name: '域名',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'normal',
    groupName: '常用维度',
    id: 'b',
    name: '应用平台',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'normal',
    groupName: '常用维度',
    id: 'cv',
    name: 'App 版本',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'user',
    groupName: '用户属性',
    id: 'usr_t_date_1',
    name: '测试日期型',
    type: 'usr',
    valueType: 'date',
  },
  {
    groupId: 'user',
    groupName: '用户属性',
    id: 'usr_t_number_1',
    name: '测试数值型',
    type: 'usr',
    valueType: 'int',
  },
  {
    groupId: 'user',
    groupName: '用户属性',
    id: 'usr_sex002',
    name: 'sex002',
    type: 'usr',
    valueType: 'string',
  },
  {
    groupId: 'origin',
    groupName: '用户来源',
    id: 'rd',
    name: '访问来源',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'origin',
    groupName: '用户来源',
    id: 'rt',
    name: '一级访问来源',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'origin',
    groupName: '用户来源',
    id: 'kw',
    name: '搜索词',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'origin',
    groupName: '用户来源',
    id: 'utm_source',
    name: '广告来源',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'origin',
    groupName: '用户来源',
    id: 'utm_campaign',
    name: '广告名称',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'origin',
    groupName: '用户来源',
    id: 'utm_content',
    name: '广告内容',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'origin',
    groupName: '用户来源',
    id: 'utm_term',
    name: '广告关键字',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'origin',
    groupName: '用户来源',
    id: 'utm_medium',
    name: '广告媒介',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'origin',
    groupName: '用户来源',
    id: 'ch',
    name: '自定义 App 渠道',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'geo',
    groupName: '地域信息',
    id: 'city',
    name: '城市',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'geo',
    groupName: '地域信息',
    id: 'region',
    name: '地区',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'geo',
    groupName: '地域信息',
    id: 'countryCode',
    name: '国家代码',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'geo',
    groupName: '地域信息',
    id: 'countryName',
    name: '国家名称',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'device',
    groupName: '设备信息',
    id: 'bw',
    name: '浏览器',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'device',
    groupName: '设备信息',
    id: 'bwv',
    name: '浏览器版本',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'device',
    groupName: '设备信息',
    id: 'os',
    name: '操作系统',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'device',
    groupName: '设备信息',
    id: 'osv',
    name: '操作系统版本',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'device',
    groupName: '设备信息',
    id: 'shw',
    name: '屏幕大小（高*宽）',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'device',
    groupName: '设备信息',
    id: 'l',
    name: '操作系统语言',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'device',
    groupName: '设备信息',
    id: 'db',
    name: '设备品牌',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'device',
    groupName: '设备信息',
    id: 'dm',
    name: '设备型号',
    type: 'global',
    valueType: null,
  },
  {
    groupId: 'device',
    groupName: '设备信息',
    id: 'o',
    name: '设备方向',
    type: 'global',
    valueType: null,
  },
  {
    id: 'AbQ3bDYe',
    isPrimaryKey: false,
    key: 'order_name',
    type: 'itm',
    groupId: 'item',
    name: 'shangpin',
    groupName: '物品属性',
    valueType: 'string',
    description: '',
  },
  {
    groupId: 'normal',
    groupName: '常用维度',
    id: 'tm',
    name:
      '时间我是超级长的名字超级长的名字超级长的名字超级长的名字超级长的名字超级长的名字超级长的名字超级长的名字超级长的名字超级长的名字超级长的名字超级长的名字超级长的名字超级长的名字',
    type: 'global',
    valueType: null,
  },
];

export const Dimensions2 = [
  {
    id: 'd',
    name: '域名',
    groupId: 'normal',
    groupName: '常用维度',
    type: 'global',
    valueType: null,
    __typename: 'Dimension',
  },
  {
    id: 'p',
    name: '页面',
    groupId: 'normal',
    groupName: '常用维度',
    type: 'global',
    valueType: null,
    __typename: 'Dimension',
  },
  {
    id: 'rp',
    name: '页面来源',
    groupId: 'normal',
    groupName: '常用维度',
    type: 'global',
    valueType: null,
    __typename: 'Dimension',
  },
  {
    id: 'b',
    name: '应用平台',
    groupId: 'normal',
    groupName: '常用维度',
    type: 'global',
    valueType: null,
    __typename: 'Dimension',
  },
  {
    id: 'cv',
    name: 'App 版本',
    groupId: 'normal',
    groupName: '常用维度',
    type: 'global',
    valueType: null,
    __typename: 'Dimension',
  },
  {
    id: 'usr_test_0118_1',
    name: '0118-1',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  { valueType: 'STRING', type: 'tag', name: '0112-列表', groupId: 'tag', groupName: '用户标签', id: 'tag_513' },
  { valueType: 'STRING', type: 'tag', name: '0112-最初-属性', groupId: 'tag', groupName: '用户标签', id: 'tag_512' },
  { valueType: 'STRING', type: 'tag', name: '0112-最多', groupId: 'tag', groupName: '用户标签', id: 'tag_509' },
  { valueType: 'STRING', type: 'tag', name: '0122-sql-集合', groupId: 'tag', groupName: '用户标签', id: 'tag_528' },
  { valueType: 'STRING', type: 'tag', name: '0308-分层', groupId: 'tag', groupName: '用户标签', id: 'tag_584' },
  { valueType: 'STRING', type: 'tag', name: '0308-列表-属性', groupId: 'tag', groupName: '用户标签', id: 'tag_583' },
  { valueType: 'STRING', type: 'tag', name: '0308-最初', groupId: 'tag', groupName: '用户标签', id: 'tag_580' },
  { valueType: 'STRING', type: 'tag', name: '0308-最大值', groupId: 'tag', groupName: '用户标签', id: 'tag_579' },
  { valueType: 'STRING', type: 'tag', name: '0310-最大', groupId: 'tag', groupName: '用户标签', id: 'tag_602' },
  { valueType: 'STRING', type: 'tag', name: '0310-最大(副本)', groupId: 'tag', groupName: '用户标签', id: 'tag_603' },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '0310-最大(副本)(副本)',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_604',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '10月上半月新增，但下半月没来',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_291',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '10月新增用户活跃分层',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_290',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '1121-1123支付成功优惠券名称列表',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_319',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '1121-1123支付成功分层',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_320',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '1121-1123最多支付成功优惠券',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_317',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '1204创建11月上半月注册但下半月未访问的用户',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_383',
  },
  { valueType: 'STRING', type: 'tag', name: '1210_sql_字符串12', groupId: 'tag', groupName: '用户标签', id: 'tag_431' },
  { valueType: 'STRING', type: 'tag', name: '1210_sql_集合', groupId: 'tag', groupName: '用户标签', id: 'tag_428' },
  { valueType: 'STRING', type: 'tag', name: '1210_分层', groupId: 'tag', groupName: '用户标签', id: 'tag_446' },
  { valueType: 'STRING', type: 'tag', name: '1210_列表', groupId: 'tag', groupName: '用户标签', id: 'tag_445' },
  { valueType: 'STRING', type: 'tag', name: '1210_最大值', groupId: 'tag', groupName: '用户标签', id: 'tag_442' },
  { valueType: 'STRING', type: 'tag', name: '1214_分层', groupId: 'tag', groupName: '用户标签', id: 'tag_455' },
  { valueType: 'STRING', type: 'tag', name: '1214_列表_属性', groupId: 'tag', groupName: '用户标签', id: 'tag_454' },
  { valueType: 'STRING', type: 'tag', name: '1214_最初_属性', groupId: 'tag', groupName: '用户标签', id: 'tag_453' },
  { valueType: 'STRING', type: 'tag', name: '1214_最大', groupId: 'tag', groupName: '用户标签', id: 'tag_450' },
  { valueType: 'STRING', type: 'tag', name: '1217_sql_字符串', groupId: 'tag', groupName: '用户标签', id: 'tag_472' },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '1217_sql_集合_update',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_471',
  },
  { valueType: 'STRING', type: 'tag', name: '1217_分层', groupId: 'tag', groupName: '用户标签', id: 'tag_474' },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '1217_分层 做过 产品交互次数 >= 大于等于 1 次',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_484',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '1217_分层 做过 产品交互次数 >= 大于等于 1 次(副本)',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_485',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '1217_分层 做过 产品交互次数 >= 大于等于 1 次(副本)(副本)',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_486',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '1217_分层 属性为test_1217_string 有值',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_488',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '1217_分层 属性为test_1217_string 没值',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_487',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '1217_分层 属性过去30天域名没值',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_476',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '1217_分层 属性过去30天性别没值',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_477',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '1217_分层 标签为日期between12.1-17号',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_480',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '1217_分层 标签为最大值not in',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_481',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '1217_分层 标签为累计值<1',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_478',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '1217_分层 注册日期 相对现在 在 过去 100 天',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_482',
  },
  { valueType: 'STRING', type: 'tag', name: '1217_分层<0', groupId: 'tag', groupName: '用户标签', id: 'tag_475' },
  { valueType: 'STRING', type: 'tag', name: '1217_列表', groupId: 'tag', groupName: '用户标签', id: 'tag_468' },
  { valueType: 'STRING', type: 'tag', name: '1217_最初_属性', groupId: 'tag', groupName: '用户标签', id: 'tag_467' },
  { valueType: 'STRING', type: 'tag', name: '1217_最大值', groupId: 'tag', groupName: '用户标签', id: 'tag_464' },
  { valueType: 'STRING', type: 'tag', name: '1224-分层', groupId: 'tag', groupName: '用户标签', id: 'tag_496' },
  { valueType: 'STRING', type: 'tag', name: '1224-分层(副本)', groupId: 'tag', groupName: '用户标签', id: 'tag_500' },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '1224-分层(副本)(副本)',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_501',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '1224-分层(副本)-负数',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_502',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '1224-魔豆-string',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_test_1224_1',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '1224-魔豆-string-double-0',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_test_1224_string_double',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '1224-魔豆-string-int',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_test_1224_string_int',
  },
  { valueType: 'STRING', type: 'tag', name: 'AAAA', groupId: 'tag', groupName: '用户标签', id: 'tag_69' },
  {
    valueType: 'STRING',
    type: 'tag',
    name: 'BC-Largest Spent on Product',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_155',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: 'BC-Last Product Purchased',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_156',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: 'BC-Products Purchased (7Day)',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_157',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: 'ClassOfFrequency:过去3个月交易天数',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_170',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: 'ClassOfMonetary:过去3个月累计交易金额',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_169',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: 'ClassOfRecency:过去3个月最近一次购买距今天数',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_168',
  },
  { valueType: 'STRING', type: 'tag', name: 'F30天活跃', groupId: 'tag', groupName: '用户标签', id: 'tag_60' },
  { valueType: 'STRING', type: 'tag', name: 'F_用户忠诚度F', groupId: 'tag', groupName: '用户标签', id: 'tag_65' },
  { valueType: 'STRING', type: 'tag', name: 'M_用户价值', groupId: 'tag', groupName: '用户标签', id: 'tag_67' },
  { valueType: 'STRING', type: 'tag', name: 'R30天访问', groupId: 'tag', groupName: '用户标签', id: 'tag_61' },
  { valueType: 'STRING', type: 'tag', name: 'R_用户活跃度', groupId: 'tag', groupName: '用户标签', id: 'tag_63' },
  { valueType: 'STRING', type: 'tag', name: 'aaaabbb(副本)', groupId: 'tag', groupName: '用户标签', id: 'tag_365' },
  { valueType: 'STRING', type: 'tag', name: 'ly活跃度测试', groupId: 'tag', groupName: '用户标签', id: 'tag_247' },
  { valueType: 'STRING', type: 'tag', name: 'rfm测试', groupId: 'tag', groupName: '用户标签', id: 'tag_256' },
  { valueType: 'STRING', type: 'tag', name: 'test', groupId: 'tag', groupName: '用户标签', id: 'tag_259' },
  { valueType: 'STRING', type: 'tag', name: 'test-liudan', groupId: 'tag', groupName: '用户标签', id: 'tag_359' },
  { valueType: 'STRING', type: 'tag', name: 'test_标签', groupId: 'tag', groupName: '用户标签', id: 'tag_68' },
  { valueType: 'STRING', type: 'tag', name: 'ttt_date', groupId: 'tag', groupName: '用户标签', id: 'tag_293' },
  { valueType: 'STRING', type: 'tag', name: 'user class', groupId: 'tag', groupName: '用户标签', id: 'tag_108' },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '【标签-列表类】-用户加购商品列表-过去30天-cxc',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_127',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '一级SKU品类金额占比',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_236',
  },
  { valueType: 'STRING', type: 'tag', name: '万达测试', groupId: 'tag', groupName: '用户标签', id: 'tag_360' },
  { valueType: 'STRING', type: 'tag', name: '万达测试2', groupId: 'tag', groupName: '用户标签', id: 'tag_361' },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '上半月访问，下半月未访问',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_287',
  },
  { valueType: 'STRING', type: 'tag', name: '下载_分层测试', groupId: 'tag', groupName: '用户标签', id: 'tag_142' },
  { valueType: 'STRING', type: 'tag', name: '付费能力等级', groupId: 'tag', groupName: '用户标签', id: 'tag_137' },
  { valueType: 'STRING', type: 'tag', name: '价值', groupId: 'tag', groupName: '用户标签', id: 'tag_267' },
  { valueType: 'STRING', type: 'tag', name: '会员到期', groupId: 'tag', groupName: '用户标签', id: 'tag_14' },
  { valueType: 'STRING', type: 'tag', name: '会员积分', groupId: 'tag', groupName: '用户标签', id: 'tag_158' },
  { valueType: 'STRING', type: 'tag', name: '会员等級', groupId: 'tag', groupName: '用户标签', id: 'tag_187' },
  { valueType: 'STRING', type: 'tag', name: '会籍顾问', groupId: 'tag', groupName: '用户标签', id: 'tag_123' },
  { valueType: 'STRING', type: 'tag', name: '促銷敏感度', groupId: 'tag', groupName: '用户标签', id: 'tag_189' },
  { valueType: 'STRING', type: 'tag', name: '促销偏好', groupId: 'tag', groupName: '用户标签', id: 'tag_12' },
  { valueType: 'STRING', type: 'tag', name: '偏好商品品类', groupId: 'tag', groupName: '用户标签', id: 'tag_78' },
  { valueType: 'STRING', type: 'tag', name: '偏好最多', groupId: 'tag', groupName: '用户标签', id: 'tag_93' },
  { valueType: 'STRING', type: 'tag', name: '分层分群测试', groupId: 'tag', groupName: '用户标签', id: 'tag_262' },
  { valueType: 'STRING', type: 'tag', name: '分层分群统一-活跃', groupId: 'tag', groupName: '用户标签', id: 'tag_433' },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '分层分群统一做过<1',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_434',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '分层分群统一做过<3',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_436',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '分层分群统一做过>0',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_437',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '分层分群统一做过>3',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_441',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '分层分群统一做过>=0',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_435',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '分层分群统一用户属性',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_438',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '分层分群统一用户标签',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_440',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '分层分群统一访问属性',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_439',
  },
  { valueType: 'STRING', type: 'tag', name: '分层标签-ZC', groupId: 'tag', groupName: '用户标签', id: 'tag_79' },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '商品偏好-cxc(副本)',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_148',
  },
  { valueType: 'STRING', type: 'tag', name: '商品点击最多的sku', groupId: 'tag', groupName: '用户标签', id: 'tag_94' },
  { valueType: 'STRING', type: 'tag', name: '商品点击热度', groupId: 'tag', groupName: '用户标签', id: 'tag_265' },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '基础标签分层标签测试',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_264',
  },
  { valueType: 'STRING', type: 'tag', name: '客户价值', groupId: 'tag', groupName: '用户标签', id: 'tag_167' },
  { valueType: 'STRING', type: 'tag', name: '性别分层', groupId: 'tag', groupName: '用户标签', id: 'tag_369' },
  { valueType: 'STRING', type: 'tag', name: '支付商品列表', groupId: 'tag', groupName: '用户标签', id: 'tag_85' },
  { valueType: 'STRING', type: 'tag', name: '支付成功列表', groupId: 'tag', groupName: '用户标签', id: 'tag_11' },
  { valueType: 'STRING', type: 'tag', name: '是否流失', groupId: 'tag', groupName: '用户标签', id: 'tag_110' },
  { valueType: 'STRING', type: 'tag', name: '是否需要人为干预', groupId: 'tag', groupName: '用户标签', id: 'tag_146' },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '最后一次购买商品名称',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_124',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '最后浏览商品详情的一级分类',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_2',
  },
  { valueType: 'STRING', type: 'tag', name: '最多访问', groupId: 'tag', groupName: '用户标签', id: 'tag_23' },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '未来30天购买可能性',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_188',
  },
  { valueType: 'STRING', type: 'tag', name: '标签名称为事件', groupId: 'tag', groupName: '用户标签', id: 'tag_112' },
  { valueType: 'STRING', type: 'tag', name: '注册一天以后', groupId: 'tag', groupName: '用户标签', id: 'tag_386' },
  { valueType: 'STRING', type: 'tag', name: '活跃度', groupId: 'tag', groupName: '用户标签', id: 'tag_72' },
  { valueType: 'STRING', type: 'tag', name: '活跃度-test111', groupId: 'tag', groupName: '用户标签', id: 'tag_241' },
  { valueType: 'STRING', type: 'tag', name: '活跃度模型-lb', groupId: 'tag', groupName: '用户标签', id: 'tag_96' },
  { valueType: 'STRING', type: 'tag', name: '流失风险', groupId: 'tag', groupName: '用户标签', id: 'tag_91' },
  { valueType: 'STRING', type: 'tag', name: '测试一级类目最多', groupId: 'tag', groupName: '用户标签', id: 'tag_252' },
  { valueType: 'STRING', type: 'tag', name: '测试属性', groupId: 'tag', groupName: '用户标签', id: 'tag_458' },
  { valueType: 'STRING', type: 'tag', name: '测试时间分层', groupId: 'tag', groupName: '用户标签', id: 'tag_457' },
  { valueType: 'STRING', type: 'tag', name: '测试时间标签', groupId: 'tag', groupName: '用户标签', id: 'tag_385' },
  { valueType: 'STRING', type: 'tag', name: '测试标签1', groupId: 'tag', groupName: '用户标签', id: 'tag_280' },
  { valueType: 'STRING', type: 'tag', name: '测试标签12', groupId: 'tag', groupName: '用户标签', id: 'tag_526' },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '浏览最多的一级商品-ZC',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_80',
  },
  { valueType: 'STRING', type: 'tag', name: '点击商品列表', groupId: 'tag', groupName: '用户标签', id: 'tag_46' },
  { valueType: 'STRING', type: 'tag', name: '生命', groupId: 'tag', groupName: '用户标签', id: 'tag_305' },
  { valueType: 'STRING', type: 'tag', name: '生命周期', groupId: 'tag', groupName: '用户标签', id: 'tag_377' },
  { valueType: 'STRING', type: 'tag', name: '生命周期-lc', groupId: 'tag', groupName: '用户标签', id: 'tag_379' },
  { valueType: 'STRING', type: 'tag', name: '用户价值分层-cxc', groupId: 'tag', groupName: '用户标签', id: 'tag_371' },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '用户价值分层-cxc（副本）',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_372',
  },
  { valueType: 'STRING', type: 'tag', name: '用户价值分层标签', groupId: 'tag', groupName: '用户标签', id: 'tag_141' },
  { valueType: 'STRING', type: 'tag', name: '用户分层', groupId: 'tag', groupName: '用户标签', id: 'tag_278' },
  { valueType: 'STRING', type: 'tag', name: '用户分层测试', groupId: 'tag', groupName: '用户标签', id: 'tag_357' },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '用户分层测试(副本)',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_358',
  },
  { valueType: 'STRING', type: 'tag', name: '用户吸引力', groupId: 'tag', groupName: '用户标签', id: 'tag_120' },
  { valueType: 'STRING', type: 'tag', name: '男装占比', groupId: 'tag', groupName: '用户标签', id: 'tag_234' },
  { valueType: 'STRING', type: 'tag', name: '组织名称', groupId: 'tag', groupName: '用户标签', id: 'tag_105' },
  { valueType: 'STRING', type: 'tag', name: '结束安装的sdk平台', groupId: 'tag', groupName: '用户标签', id: 'tag_191' },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '被售卖最多次数的销售-CC',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_56',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '被最初售卖的销售-CC',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_57',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '被最近一次售卖的销售-CC',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_58',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '订单支付成功次数最多的商品',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_283',
  },
  { valueType: 'STRING', type: 'tag', name: '访问次数', groupId: 'tag', groupName: '用户标签', id: 'tag_113' },
  { valueType: 'STRING', type: 'tag', name: '购买意向', groupId: 'tag', groupName: '用户标签', id: 'tag_132' },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '购买最多的商品-cxc',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_128',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '购买最多的商品品类-cxc',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_136',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '过去2周浏览最多的商品分类',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_180',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '过去2周购买的商品分类',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_181',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '过去30天最后一次购买的商品品类（一级品类）',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_301',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '过去30天订单支付成功的商品品类',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_274',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '过去30天购买一级分类数量最多',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_9',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '过去7天浏览最多的商品类型（一级品类）-tst',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_298',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '过去7天购买最多的商品类型（一级品类）',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_299',
  },
  {
    valueType: 'STRING',
    type: 'tag',
    name: '过去一周最近一次线上咨询内容',
    groupId: 'tag',
    groupName: '用户标签',
    id: 'tag_184',
  },
  {
    id: 'usr_fdsd',
    name: '测试变量前缀',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_imgOpenCnt_usr',
    name: '触达APP图片点击次数',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_phone',
    name: '触达登录用户手机号',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_gio_push_device_brand_usr',
    name: '触达推送通道',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_CreateAt',
    name: '触达注册日期',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_$basic_birthday',
    name: '出生年月日',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'date',
    __typename: 'Dimension',
  },
  {
    id: 'usr_waefwe_wfa',
    name: '大大大',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_popWindowSoloClick',
    name: '弹窗的点击--用户细查',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_popWindowSoloClose',
    name: '弹窗的关闭--用户细查',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_popWindowSoloImp',
    name: '弹窗的展示--用户细查',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_dept',
    name: '负责部门',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_gpush_test1',
    name: 'GPush测试数据',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_new_gpush_test1',
    name: 'GPush测试数据1',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_new_gpush_test2',
    name: 'GPush测试数据2',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_homepage_cta',
    name: '官网首页CTA文案的A/B分组测试',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_$wechat_subscribeList',
    name: '关注公众号',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_huiyuanka',
    name: '会员卡名称',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_life_cycle_ppl',
    name: '生命周期',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_isPayed_ppl',
    name: '是否付费（用户变量）',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_gio_push_package',
    name: '推送包名',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_gio_push_token',
    name: '推送令牌',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_gio_push_channel_usr',
    name: '推送通道',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_number_of_completed_tasks',
    name: '完成任务个数（最近）',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_$wechat_city',
    name: '微信用户所在城市',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_$wechat_country',
    name: '微信用户所在国家',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_$wechat_province',
    name: '微信用户所在省份',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_$wechat_gender',
    name: '微信用户性别',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_$wechat_language',
    name: '微信语言',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_sex',
    name: '性别',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_$basic_gender',
    name: '性别',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_user_created_at',
    name: '用户创建时间',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_user_name',
    name: '用户名称',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_preference',
    name: '用户偏好',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_user_life_cycle_recent',
    name: '用户生命周期时间（按周|最近）',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_user_life_cycle_final',
    name: '用户生命周期时间（按周|最终）',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_IfUserBuy_ppl',
    name: '用户是否购买',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_user_dept',
    name: '用户所属部门',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_city_usr',
    name: '用户着陆城市',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_createdat',
    name: '用户注册日期',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_test_int',
    name: '整数',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'int',
    __typename: 'Dimension',
  },
  {
    id: 'usr_faga',
    name: '证书',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'date',
    __typename: 'Dimension',
  },
  {
    id: 'usr_$alipay_isCertified',
    name: '支付宝实名认证',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_$alipay_isStudentCertified',
    name: '支付宝学生认证',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_$alipay_userType',
    name: '支付宝用户类型',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_$alipay_city',
    name: '支付宝用户所在城市',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_$alipay_province',
    name: '支付宝用户所在省份',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_$alipay_gender',
    name: '支付宝用户性别',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_$alipay_userStatus',
    name: '支付宝用户状态',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_test_date_1',
    name: '注册日期',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'date',
    __typename: 'Dimension',
  },
  {
    id: 'usr_$basic_createdAt',
    name: '注册时间',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'date',
    __typename: 'Dimension',
  },
  {
    id: 'usr_organization_name',
    name: '组织名称',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_organization_life_cycle_recent',
    name: '组织生命周期时间（按月|最近）',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_organization_life_cycle_final',
    name: '组织生命周期时间（按月|最终）',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_age_usr',
    name: 'age',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_df',
    name: 'fdffffffff',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'date',
    __typename: 'Dimension',
  },
  {
    id: 'usr_project',
    name: 'project',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_project_name_usr',
    name: 'project_name',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_sales',
    name: 'sales',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_test_1210_int_usr',
    name: 'test_1210_intdfd',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'int',
    __typename: 'Dimension',
  },
  {
    id: 'usr_test_1217_date',
    name: 'test_1217_date',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'date',
    __typename: 'Dimension',
  },
  {
    id: 'usr_test_1217_int',
    name: 'test_1217_int',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'int',
    __typename: 'Dimension',
  },
  {
    id: 'usr_test_1217_string',
    name: 'test_1217_string',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'usr_vars_people_VLXO',
    name: 'vars_people_VLXO',
    groupId: 'user',
    groupName: '用户属性',
    type: 'usr',
    valueType: 'string',
    __typename: 'Dimension',
  },
  {
    id: 'rd',
    name: '访问来源',
    groupId: 'origin',
    groupName: '用户来源',
    type: 'global',
    valueType: null,
    __typename: 'Dimension',
  },
  {
    id: 'rt',
    name: '一级访问来源',
    groupId: 'origin',
    groupName: '用户来源',
    type: 'global',
    valueType: null,
    __typename: 'Dimension',
  },
  {
    id: 'kw',
    name: '搜索词',
    groupId: 'origin',
    groupName: '用户来源',
    type: 'global',
    valueType: null,
    __typename: 'Dimension',
  },
  {
    id: 'utm_source',
    name: '广告来源',
    groupId: 'origin',
    groupName: '用户来源',
    type: 'global',
    valueType: null,
    __typename: 'Dimension',
  },
  {
    id: 'utm_campaign',
    name: '广告名称',
    groupId: 'origin',
    groupName: '用户来源',
    type: 'global',
    valueType: null,
    __typename: 'Dimension',
  },
  {
    id: 'utm_content',
    name: '广告内容',
    groupId: 'origin',
    groupName: '用户来源',
    type: 'global',
    valueType: null,
    __typename: 'Dimension',
  },
  {
    id: 'utm_term',
    name: '广告关键字',
    groupId: 'origin',
    groupName: '用户来源',
    type: 'global',
    valueType: null,
    __typename: 'Dimension',
  },
  {
    id: 'utm_medium',
    name: '广告媒介',
    groupId: 'origin',
    groupName: '用户来源',
    type: 'global',
    valueType: null,
    __typename: 'Dimension',
  },
  {
    id: 'ch',
    name: '自定义 App 渠道',
    groupId: 'origin',
    groupName: '用户来源',
    type: 'global',
    valueType: null,
    __typename: 'Dimension',
  },
  {
    id: 'city',
    name: '城市',
    groupId: 'geo',
    groupName: '地域信息',
    type: 'global',
    valueType: null,
    __typename: 'Dimension',
  },
  {
    id: 'region',
    name: '地区',
    groupId: 'geo',
    groupName: '地域信息',
    type: 'global',
    valueType: null,
    __typename: 'Dimension',
  },
  {
    id: 'countryCode',
    name: '国家代码',
    groupId: 'geo',
    groupName: '地域信息',
    type: 'global',
    valueType: null,
    __typename: 'Dimension',
  },
  {
    id: 'countryName',
    name: '国家名称',
    groupId: 'geo',
    groupName: '地域信息',
    type: 'global',
    valueType: null,
    __typename: 'Dimension',
  },
  {
    id: 'bw',
    name: '浏览器',
    groupId: 'device',
    groupName: '设备信息',
    type: 'global',
    valueType: null,
    __typename: 'Dimension',
  },
  {
    id: 'bwv',
    name: '浏览器版本',
    groupId: 'device',
    groupName: '设备信息',
    type: 'global',
    valueType: null,
    __typename: 'Dimension',
  },
  {
    id: 'os',
    name: '操作系统',
    groupId: 'device',
    groupName: '设备信息',
    type: 'global',
    valueType: null,
    __typename: 'Dimension',
  },
  {
    id: 'osv',
    name: '操作系统版本',
    groupId: 'device',
    groupName: '设备信息',
    type: 'global',
    valueType: null,
    __typename: 'Dimension',
  },
  {
    id: 'shw',
    name: '屏幕大小（高*宽）',
    groupId: 'device',
    groupName: '设备信息',
    type: 'global',
    valueType: null,
    __typename: 'Dimension',
  },
  {
    id: 'l',
    name: '操作系统语言',
    groupId: 'device',
    groupName: '设备信息',
    type: 'global',
    valueType: null,
    __typename: 'Dimension',
  },
  {
    id: 'db',
    name: '设备品牌',
    groupId: 'device',
    groupName: '设备信息',
    type: 'global',
    valueType: null,
    __typename: 'Dimension',
  },
  {
    id: 'dm',
    name: '设备型号',
    groupId: 'device',
    groupName: '设备信息',
    type: 'global',
    valueType: null,
    __typename: 'Dimension',
  },
  {
    id: 'o',
    name: '设备方向',
    groupId: 'device',
    groupName: '设备信息',
    type: 'global',
    valueType: null,
    __typename: 'Dimension',
  },
];
