export const spaceTags = [
  {
    id: 'JnG40OGz',
    name: '是',
    creator: 'haozhigang',
    creatorId: 'rRGoYQml',
    createdAt: '2021-01-14T07:08:25Z',
    updater: 'haozhigang',
    updaterId: 'rRGoYQml',
    updatedAt: '2021-01-14T07:08:25Z',
    description: '是  得到的',
    platforms: ['minp'],
    docType: 'page',
    actions: ['page'],
    patternMatched: false,
    attrs: {
      content: null,
      index: null,
      href: null,
      path: 'pages/index/index',
      pg: null,
      query: null,
      xpath: null,
      contentType: null,
      domain: 'wx123456',
      urlScheme: null,
      __typename: 'DocProps',
    },
    definition: {
      domain: 'wx123456',
      path: 'pages/index/index',
      query: '得到的=s',
      xpath: null,
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: null,
      __typename: 'DocProps',
    },
    screenshot: { target: '', viewport: '', __typename: 'Screenshot' },
    __typename: 'Element',
  },
  {
    id: 'zZDb6aD9',
    name: '1月13，21次',
    creator: 'lvyuqiang',
    creatorId: 'n1QVaDyR',
    createdAt: '2021-01-13T09:03:46Z',
    updater: 'lvyuqiang',
    updaterId: 'n1QVaDyR',
    updatedAt: '2021-01-13T09:03:46Z',
    description: '1月13，21次',
    platforms: ['minp'],
    docType: 'page',
    actions: ['page'],
    patternMatched: false,
    attrs: {
      content: null,
      index: null,
      href: null,
      path: 'pages/index/index',
      pg: null,
      query: null,
      xpath: null,
      contentType: null,
      domain: 'wx123456',
      urlScheme: null,
      __typename: 'DocProps',
    },
    definition: {
      domain: 'wx123456',
      path: 'pages/index/index',
      query: null,
      xpath: null,
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: null,
      __typename: 'DocProps',
    },
    screenshot: { target: '', viewport: '', __typename: 'Screenshot' },
    __typename: 'Element',
  },
  {
    id: 'mgGJy2pA',
    name: 'wx123 的是页面 pages/form/form 。',
    creator: 'lvyuqiang',
    creatorId: 'n1QVaDyR',
    createdAt: '2021-01-13T07:14:25Z',
    updater: 'lvyuqiang',
    updaterId: 'n1QVaDyR',
    updatedAt: '2021-01-13T07:14:25Z',
    description: '现在定义的是页面 pages/form/form 。',
    platforms: ['minp'],
    docType: 'page',
    actions: ['page'],
    patternMatched: false,
    attrs: {
      content: null,
      index: null,
      href: null,
      path: 'pages/form/form',
      pg: null,
      query: null,
      xpath: null,
      contentType: null,
      domain: 'wx123456',
      urlScheme: null,
      __typename: 'DocProps',
    },
    definition: {
      domain: 'wx123456',
      path: 'pages/form/form',
      query: null,
      xpath: null,
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: null,
      __typename: 'DocProps',
    },
    screenshot: { target: '', viewport: '', __typename: 'Screenshot' },
    __typename: 'Element',
  },
  {
    id: 'AVpZWyGK',
    name: 'ls-xl',
    creator: 'liushuo',
    creatorId: 'qgQMnp3L',
    createdAt: '2021-01-12T05:14:29Z',
    updater: 'liushuo',
    updaterId: 'qgQMnp3L',
    updatedAt: '2021-01-12T05:14:29Z',
    description: '',
    platforms: ['web'],
    docType: 'elem',
    actions: ['chng'],
    patternMatched: false,
    attrs: {
      content: null,
      index: null,
      href: null,
      path: '/push/cdp/testgio-cdpcircel.html',
      pg: null,
      query: null,
      xpath: '/div.main/div.title/form.basic-grey/label/select.selection',
      contentType: null,
      domain: 'release-messages.growingio.cn',
      urlScheme: null,
      __typename: 'DocProps',
    },
    definition: {
      domain: 'release-messages.growingio.cn',
      path: '/push/cdp/testgio-cdpcircel.html',
      query: null,
      xpath: '/div.title/form.basic-grey/label/select.selection',
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: null,
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/07b18645-b784-4abe-b973-a08605bf5893.jpg?sign=wcyjkYl8LHTacSHpdojrXHeTrHPzHONADaFNg5OBY3U%3D&expires=1611037476177',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: 'WkDyn8Qe',
    name: 'ls-jk',
    creator: 'liushuo',
    creatorId: 'qgQMnp3L',
    createdAt: '2021-01-12T05:13:53Z',
    updater: 'liushuo',
    updaterId: 'qgQMnp3L',
    updatedAt: '2021-01-12T05:13:53Z',
    description: '',
    platforms: ['web'],
    docType: 'elem',
    actions: ['clck'],
    patternMatched: false,
    attrs: {
      content: '查找 query 柯基图片',
      index: null,
      href:
        'https://www.google.com/search?q=%E6%9F%AF%E5%9F%BA%E5%9B%BE%E7%89%87&oq=%E6%9F%AF%E5%9F%BA%E5%9B%BE%E7%89%87&aqs=chrome..69i57j0l2j69i61j69i60j0.4959j0j4&sourceid=chrome&ie=UTF-8',
      path: '/push/cdp/testgio-cdpcircel.html',
      pg: null,
      query: null,
      xpath: '/div.main/div.title/form.basic-grey/a',
      contentType: null,
      domain: 'release-messages.growingio.cn',
      urlScheme: null,
      __typename: 'DocProps',
    },
    definition: {
      domain: 'release-messages.growingio.cn',
      path: '/push/cdp/testgio-cdpcircel.html',
      query: null,
      xpath: '/div.main/div.title/form.basic-grey/a',
      index: null,
      href: null,
      content: '查找 query 柯基图片',
      pg: null,
      contentType: '=',
      urlScheme: null,
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/364c9f7b-9a27-47c5-94d2-bfe193e3c89a.jpg?sign=bFYchAI2ahfGZykwMOZL3Pm6NBYfc2srQPXu6jt8cC8%3D&expires=1611037476177',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: 'kqQe1qQr',
    name: '定义一个新的事件2',
    creator: 'zhangxueqi',
    creatorId: 'oNGzxQgB',
    createdAt: '2021-01-08T06:21:14Z',
    updater: 'zhangxueqi',
    updaterId: 'oNGzxQgB',
    updatedAt: '2021-01-08T06:21:14Z',
    description: '',
    platforms: ['minp'],
    docType: 'elem',
    actions: ['clck'],
    patternMatched: false,
    attrs: {
      content: '主页',
      index: '0',
      href: 'pages/index/index',
      path: 'pages/index/index',
      pg: null,
      query: null,
      xpath: '#onTabItemTap',
      contentType: null,
      domain: 'wx265d0fa6fa70fae9',
      urlScheme: null,
      __typename: 'DocProps',
    },
    definition: {
      domain: 'wx265d0fa6fa70fae9',
      path: 'pages/index/index',
      query: '12=12',
      xpath: '#onTabItemTap',
      index: '0',
      href: 'pages/index/index',
      content: '主页',
      pg: null,
      contentType: '=',
      urlScheme: null,
      __typename: 'DocProps',
    },
    screenshot: { target: '', viewport: '', __typename: 'Screenshot' },
    __typename: 'Element',
  },
  {
    id: '7RDYqYDA',
    name: '事件2的页面',
    creator: 'zhangxueqi',
    creatorId: 'oNGzxQgB',
    createdAt: '2021-01-08T06:20:52Z',
    updater: 'zhangxueqi',
    updaterId: 'oNGzxQgB',
    updatedAt: '2021-01-08T06:20:52Z',
    description: '',
    platforms: ['minp'],
    docType: 'page',
    actions: ['page'],
    patternMatched: false,
    attrs: {
      content: null,
      index: null,
      href: null,
      path: 'pages/index/index',
      pg: null,
      query: null,
      xpath: null,
      contentType: null,
      domain: 'wx265d0fa6fa70fae9',
      urlScheme: null,
      __typename: 'DocProps',
    },
    definition: {
      domain: 'wx265d0fa6fa70fae9',
      path: 'pages/index/index',
      query: '12=12',
      xpath: null,
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: null,
      __typename: 'DocProps',
    },
    screenshot: { target: '', viewport: '', __typename: 'Screenshot' },
    __typename: 'Element',
  },
  {
    id: 'ExQWkgQ7',
    name: '事件4',
    creator: 'zhangxueqi',
    creatorId: 'oNGzxQgB',
    createdAt: '2021-01-08T06:19:40Z',
    updater: 'zhangxueqi',
    updaterId: 'oNGzxQgB',
    updatedAt: '2021-01-08T06:19:40Z',
    description: '',
    platforms: ['minp'],
    docType: 'page',
    actions: ['page'],
    patternMatched: false,
    attrs: {
      content: null,
      index: null,
      href: null,
      path: 'pages/index/index',
      pg: null,
      query: null,
      xpath: null,
      contentType: null,
      domain: 'wx265d0fa6fa70fae9',
      urlScheme: null,
      __typename: 'DocProps',
    },
    definition: {
      domain: 'wx265d0fa6fa70fae9',
      path: 'pages/index/index',
      query: null,
      xpath: null,
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: null,
      __typename: 'DocProps',
    },
    screenshot: { target: '', viewport: '', __typename: 'Screenshot' },
    __typename: 'Element',
  },
  {
    id: 'bVG246Q6',
    name: '事件3',
    creator: 'zhangxueqi',
    creatorId: 'oNGzxQgB',
    createdAt: '2021-01-08T06:19:09Z',
    updater: 'zhangxueqi',
    updaterId: 'oNGzxQgB',
    updatedAt: '2021-01-08T06:19:09Z',
    description: '77777777',
    platforms: ['minp'],
    docType: 'page',
    actions: ['page'],
    patternMatched: false,
    attrs: {
      content: null,
      index: null,
      href: null,
      path: 'pages/index/index',
      pg: null,
      query: null,
      xpath: null,
      contentType: null,
      domain: 'wx265d0fa6fa70fae9',
      urlScheme: null,
      __typename: 'DocProps',
    },
    definition: {
      domain: 'wx265d0fa6fa70fae9',
      path: 'pages/index/index',
      query: '234234=32',
      xpath: null,
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: null,
      __typename: 'DocProps',
    },
    screenshot: { target: '', viewport: '', __typename: 'Screenshot' },
    __typename: 'Element',
  },
  {
    id: 'nxGKZxpa',
    name: '事件2',
    creator: 'zhangxueqi',
    creatorId: 'oNGzxQgB',
    createdAt: '2021-01-08T06:16:53Z',
    updater: 'zhangxueqi',
    updaterId: 'oNGzxQgB',
    updatedAt: '2021-01-08T06:16:53Z',
    description: '',
    platforms: ['minp'],
    docType: 'elem',
    actions: ['clck'],
    patternMatched: false,
    attrs: {
      content: '主页',
      index: '0',
      href: 'pages/index/index',
      path: 'pages/index/index',
      pg: null,
      query: null,
      xpath: '#onTabItemTap',
      contentType: null,
      domain: 'wx265d0fa6fa70fae9',
      urlScheme: null,
      __typename: 'DocProps',
    },
    definition: {
      domain: 'wx265d0fa6fa70fae9',
      path: 'pages/index/index',
      query: 'aaa=bbb',
      xpath: '#onTabItemTap',
      index: '0',
      href: 'pages/index/index',
      content: null,
      pg: null,
      contentType: null,
      urlScheme: null,
      __typename: 'DocProps',
    },
    screenshot: { target: '', viewport: '', __typename: 'Screenshot' },
    __typename: 'Element',
  },
  {
    id: 'zqQR25Qo',
    name: '事件1',
    creator: 'zhangxueqi',
    creatorId: 'oNGzxQgB',
    createdAt: '2021-01-08T06:14:10Z',
    updater: 'zhangxueqi',
    updaterId: 'oNGzxQgB',
    updatedAt: '2021-01-08T06:14:10Z',
    description: '',
    platforms: ['minp'],
    docType: 'elem',
    actions: ['clck'],
    patternMatched: false,
    attrs: {
      content: '主页',
      index: '0',
      href: 'pages/index/index',
      path: 'pages/index/index',
      pg: null,
      query: null,
      xpath: '#onTabItemTap',
      contentType: null,
      domain: 'wx265d0fa6fa70fae9',
      urlScheme: null,
      __typename: 'DocProps',
    },
    definition: {
      domain: 'wx265d0fa6fa70fae9',
      path: 'pages/index/index',
      query: 'aaa=bbb',
      xpath: '#onTabItemTap',
      index: '0',
      href: 'pages/index/index',
      content: '0000',
      pg: null,
      contentType: '=',
      urlScheme: null,
      __typename: 'DocProps',
    },
    screenshot: { target: '', viewport: '', __typename: 'Screenshot' },
    __typename: 'Element',
  },
  {
    id: 'wWDrjvDM',
    name: '加一份奶盖',
    creator: 'zhangxueqi',
    creatorId: 'oNGzxQgB',
    createdAt: '2021-01-08T06:11:09Z',
    updater: 'zhangxueqi',
    updaterId: 'oNGzxQgB',
    updatedAt: '2021-01-08T06:11:09Z',
    description: '小摩托',
    platforms: ['minp'],
    docType: 'elem',
    actions: ['clck'],
    patternMatched: false,
    attrs: {
      content: '主页',
      index: '0',
      href: 'pages/index/index',
      path: 'pages/index/index',
      pg: null,
      query: null,
      xpath: '#onTabItemTap',
      contentType: null,
      domain: 'wx265d0fa6fa70fae9',
      urlScheme: null,
      __typename: 'DocProps',
    },
    definition: {
      domain: 'wx265d0fa6fa70fae9',
      path: 'pages/index/index',
      query: 'aaa=bbb',
      xpath: '#onTabItemTap',
      index: null,
      href: 'pages/index/index',
      content: null,
      pg: null,
      contentType: null,
      urlScheme: null,
      __typename: 'DocProps',
    },
    screenshot: { target: '', viewport: '', __typename: 'Screenshot' },
    __typename: 'Element',
  },
  {
    id: 'klGvBYG7',
    name: '整站页面',
    creator: 'likangle',
    creatorId: 'zqQR3po3',
    createdAt: '2021-01-08T04:53:33Z',
    updater: 'likangle',
    updaterId: 'zqQR3po3',
    updatedAt: '2021-01-08T04:53:33Z',
    description: '',
    platforms: ['web'],
    docType: 'page',
    actions: ['page'],
    patternMatched: false,
    attrs: {
      content: null,
      index: null,
      href: null,
      path: '/push/cdp/testgio-cdpcircel.html',
      pg: null,
      query: null,
      xpath: null,
      contentType: null,
      domain: 'release-messages.growingio.cn',
      urlScheme: null,
      __typename: 'DocProps',
    },
    definition: {
      domain: 'release-messages.growingio.cn',
      path: null,
      query: null,
      xpath: null,
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: null,
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/7e0a85db-1edc-4d0a-a607-e531337cb643.jpg?sign=roa3BYXVdQpnnUckmxuSJ8AaupssR71CSB9l0Y1Ft5k%3D&expires=1611037476177',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: 'rRGoj8pm',
    name: '点我按钮',
    creator: 'likangle',
    creatorId: 'zqQR3po3',
    createdAt: '2021-01-08T04:53:12Z',
    updater: 'likangle',
    updaterId: 'zqQR3po3',
    updatedAt: '2021-01-08T04:53:12Z',
    description: '',
    platforms: ['web'],
    docType: 'elem',
    actions: ['clck'],
    patternMatched: false,
    attrs: {
      content: '点我跳转本地页面 test.html',
      index: null,
      href: './test.html',
      path: '/push/cdp/testgio-cdpcircel.html',
      pg: null,
      query: null,
      xpath: '/div.main/div.title/form.basic-grey/a',
      contentType: null,
      domain: 'release-messages.growingio.cn',
      urlScheme: null,
      __typename: 'DocProps',
    },
    definition: {
      domain: 'release-messages.growingio.cn',
      path: '/push/cdp/testgio-cdpcircel.html',
      query: null,
      xpath: '/div.main/div.title/form.basic-grey/a',
      index: null,
      href: './test.html',
      content: null,
      pg: null,
      contentType: null,
      urlScheme: null,
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/29c00bdf-291b-47bd-b2ad-d579c4d51db3.jpg?sign=carQlSar9ZNyvSfJc1p4nXQViu5r%2FCsibk95BsT659s%3D&expires=1611037476177',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: 'n1QVdoGy',
    name: '设置用户属性',
    creator: 'likangle',
    creatorId: 'zqQR3po3',
    createdAt: '2021-01-08T04:51:59Z',
    updater: 'likangle',
    updaterId: 'zqQR3po3',
    updatedAt: '2021-01-08T04:51:59Z',
    description: '',
    platforms: ['web'],
    docType: 'elem',
    actions: ['clck'],
    patternMatched: false,
    attrs: {
      content: '设置用户属性',
      index: null,
      href: null,
      path: '/push/cdp/testgio-cdpcircel.html',
      pg: null,
      query: null,
      xpath: '/div.main/div.title/div/div.title/button',
      contentType: null,
      domain: 'release-messages.growingio.cn',
      urlScheme: null,
      __typename: 'DocProps',
    },
    definition: {
      domain: 'release-messages.growingio.cn',
      path: '/push/cdp/testgio-cdpcircel.html',
      query: null,
      xpath: '/div.title/div/div.title/button',
      index: null,
      href: null,
      content: '*属性',
      pg: null,
      contentType: 'match_phrase',
      urlScheme: null,
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/bea5f370-b785-4394-b74a-ab8025ce0ba3.jpg?sign=9xzkUIX6dF7SwvZAgT9CfLiLNkLIPjrf4l3vmm4ih74%3D&expires=1611037476177',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: 'AbQ343pY',
    name: '柯基图片按钮',
    creator: 'likangle',
    creatorId: 'zqQR3po3',
    createdAt: '2021-01-08T04:51:26Z',
    updater: 'likangle',
    updaterId: 'zqQR3po3',
    updatedAt: '2021-01-08T04:51:26Z',
    description: '',
    platforms: ['web'],
    docType: 'elem',
    actions: ['clck'],
    patternMatched: false,
    attrs: {
      content: '查找 query 柯基图片',
      index: null,
      href:
        'https://www.google.com/search?q=%E6%9F%AF%E5%9F%BA%E5%9B%BE%E7%89%87&oq=%E6%9F%AF%E5%9F%BA%E5%9B%BE%E7%89%87&aqs=chrome..69i57j0l2j69i61j69i60j0.4959j0j4&sourceid=chrome&ie=UTF-8',
      path: '/push/cdp/testgio-cdpcircel.html',
      pg: null,
      query: null,
      xpath: '/div.main/div.title/form.basic-grey/a',
      contentType: null,
      domain: 'release-messages.growingio.cn',
      urlScheme: null,
      __typename: 'DocProps',
    },
    definition: {
      domain: 'release-messages.growingio.cn',
      path: '/push/cdp/testgio-cdpcircel.html',
      query: null,
      xpath: '/div.main/div.title/form.basic-grey/a',
      index: null,
      href:
        'https://www.google.com/search?q=%E6%9F%AF%E5%9F%BA%E5%9B%BE%E7%89%87&oq=%E6%9F%AF%E5%9F%BA%E5%9B%BE%E7%89%87&aqs=chrome..69i57j0l2j69i61j69i60j0.4959j0j4&sourceid=chrome&ie=UTF-8',
      content: '查找 query 柯基图片',
      pg: null,
      contentType: '=',
      urlScheme: null,
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/65677126-d892-482d-924c-fee635f712ba.jpg?sign=%2B8MdkztR4zAm5X0LBh2MJqaG6CkDvQJk4T8BmLyPCAA%3D&expires=1611037476177',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: 'y9pm1Wpm',
    name: 'web页面定义',
    creator: 'likangle',
    creatorId: 'zqQR3po3',
    createdAt: '2021-01-08T04:50:53Z',
    updater: 'likangle',
    updaterId: 'zqQR3po3',
    updatedAt: '2021-01-08T04:50:53Z',
    description: '',
    platforms: ['web'],
    docType: 'page',
    actions: ['page'],
    patternMatched: false,
    attrs: {
      content: null,
      index: null,
      href: null,
      path: '/push/cdp/testgio-cdpcircel.html',
      pg: null,
      query: null,
      xpath: null,
      contentType: null,
      domain: 'release-messages.growingio.cn',
      urlScheme: null,
      __typename: 'DocProps',
    },
    definition: {
      domain: 'release-messages.growingio.cn',
      path: '/push/cdp/testgio-cdpcircel.html',
      query: null,
      xpath: null,
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: null,
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/b0494c82-8d0c-4640-894f-3af43dcb0d3f.jpg?sign=CF0lCh6UvtxHNe3s7P3FpsaD2fJehXXToAOygVp3CV0%3D&expires=1611037476177',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: 'rRGojYpm',
    name: 'test_测试新定义页面',
    creator: 'chenjianzhong',
    creatorId: 'evp9kDOx',
    createdAt: '2021-01-07T03:34:31Z',
    updater: 'chenjianzhong',
    updaterId: 'evp9kDOx',
    updatedAt: '2021-01-07T03:34:31Z',
    description: '',
    platforms: ['minp'],
    docType: 'page',
    actions: ['page'],
    patternMatched: false,
    attrs: {
      content: null,
      index: null,
      href: null,
      path: 'pages/form/form',
      pg: null,
      query: null,
      xpath: null,
      contentType: null,
      domain: 'wx265d0fa6fa70fae9',
      urlScheme: null,
      __typename: 'DocProps',
    },
    definition: {
      domain: 'wx265d0fa6fa70fae9',
      path: 'pages/form/form',
      query: 'id=1',
      xpath: null,
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: null,
      __typename: 'DocProps',
    },
    screenshot: { target: '', viewport: '', __typename: 'Screenshot' },
    __typename: 'Element',
  },
  {
    id: 'J1GlMEDj',
    name: '测试页面 主',
    creator: 'likangle',
    creatorId: 'zqQR3po3',
    createdAt: '2020-12-30T09:32:23Z',
    updater: 'likangle',
    updaterId: 'zqQR3po3',
    updatedAt: '2020-12-30T09:32:23Z',
    description: '',
    platforms: ['iOS'],
    docType: 'page',
    actions: ['page'],
    patternMatched: false,
    attrs: {
      content: null,
      index: null,
      href: null,
      path: '/UITabBarController',
      pg: null,
      query: null,
      xpath: null,
      contentType: null,
      domain: 'GrowingIO.GrowingIOTest-',
      urlScheme: 'growing.2c3914401a232d99',
      __typename: 'DocProps',
    },
    definition: {
      domain: 'GrowingIO.GrowingIOTest-',
      path: '/UITabBarController',
      query: null,
      xpath: null,
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: 'growing.2c3914401a232d99',
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/0b057912-9f82-4330-bdbc-d6a4ae894512.jpg?sign=ii3AkkcmQird2XFuw8usiYExahN0WBWnXRUnTKNyyOU%3D&expires=1611037476177',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: 'KnGnakpR',
    name: 'test_元素点击小程序',
    creator: 'mayutong',
    creatorId: 'nxGK0Da6',
    createdAt: '2020-12-30T08:19:21Z',
    updater: 'mayutong',
    updaterId: 'nxGK0Da6',
    updatedAt: '2020-12-30T09:14:12Z',
    description: 'test',
    platforms: ['minp'],
    docType: 'elem',
    actions: ['clck'],
    patternMatched: false,
    attrs: {
      content: '主页',
      index: '0',
      href: 'pages/index/index',
      path: 'pages/index/index',
      pg: null,
      query: null,
      xpath: '#onTabItemTap',
      contentType: null,
      domain: 'wx265d0fa6fa70fae9',
      urlScheme: null,
      __typename: 'DocProps',
    },
    definition: {
      domain: 'wx265d0fa6fa70fae9',
      path: 'pages/index/index',
      query: 'aaa=bbb',
      xpath: '#onTabItemTap',
      index: '0',
      href: null,
      content: '主页',
      pg: null,
      contentType: '=',
      urlScheme: null,
      __typename: 'DocProps',
    },
    screenshot: { target: '', viewport: '', __typename: 'Screenshot' },
    __typename: 'Element',
  },
  {
    id: 'yJQA67p1',
    name: 'test_所属页面小程序',
    creator: 'mayutong',
    creatorId: 'nxGK0Da6',
    createdAt: '2020-12-30T08:17:27Z',
    updater: 'mayutong',
    updaterId: 'nxGK0Da6',
    updatedAt: '2020-12-30T09:14:00Z',
    description: '路径打开',
    platforms: ['minp'],
    docType: 'page',
    actions: ['page'],
    patternMatched: false,
    attrs: {
      content: null,
      index: null,
      href: null,
      path: 'pages/index/index',
      pg: null,
      query: null,
      xpath: null,
      contentType: null,
      domain: 'wx265d0fa6fa70fae9',
      urlScheme: null,
      __typename: 'DocProps',
    },
    definition: {
      domain: 'wx265d0fa6fa70fae9',
      path: 'pages/index/index',
      query: 'aaa=bbb',
      xpath: null,
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: null,
      __typename: 'DocProps',
    },
    screenshot: { target: '', viewport: '', __typename: 'Screenshot' },
    __typename: 'Element',
  },
  {
    id: 'weDq7mpE',
    name: 'test小程序',
    creator: 'mayutong',
    creatorId: 'nxGK0Da6',
    createdAt: '2020-12-30T06:01:14Z',
    updater: 'mayutong',
    updaterId: 'nxGK0Da6',
    updatedAt: '2020-12-30T09:14:38Z',
    description: 'test',
    platforms: ['minp'],
    docType: 'page',
    actions: ['page'],
    patternMatched: false,
    attrs: {
      content: null,
      index: null,
      href: null,
      path: 'pages/index/index',
      pg: null,
      query: null,
      xpath: null,
      contentType: null,
      domain: 'wx265d0fa6fa70fae9',
      urlScheme: null,
      __typename: 'DocProps',
    },
    definition: {
      domain: 'wx265d0fa6fa70fae9',
      path: null,
      query: 'qqq=www',
      xpath: null,
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: null,
      __typename: 'DocProps',
    },
    screenshot: { target: '', viewport: '', __typename: 'Screenshot' },
    __typename: 'Element',
  },
  {
    id: 'MvDB8VpO',
    name: '想要测试一下选择页面的交互',
    creator: 'zhangxueqi',
    creatorId: 'oNGzxQgB',
    createdAt: '2020-12-30T05:30:57Z',
    updater: 'zhangxueqi',
    updaterId: 'oNGzxQgB',
    updatedAt: '2020-12-30T05:30:57Z',
    description: '',
    platforms: ['iOS'],
    docType: 'page',
    actions: ['page'],
    patternMatched: false,
    attrs: {
      content: null,
      index: null,
      href: null,
      path: '/UITabBarController/UINavigationController[1]/GIOBannerAndTableViewController[0]',
      pg: null,
      query: null,
      xpath: null,
      contentType: null,
      domain: 'GrowingIO.GrowingIOTest-1221',
      urlScheme: 'growing.2c3914401a232d99',
      __typename: 'DocProps',
    },
    definition: {
      domain: 'GrowingIO.GrowingIOTest-1221',
      path: '/UITabBarController/UINavigationController[1]/GIOBannerAndTableViewController[0]',
      query: null,
      xpath: null,
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: 'growing.2c3914401a232d99',
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/b15926bd-297e-4637-b46e-29e0082b49fe.jpg?sign=pBWgfO9Z3ihLyF6vMc9UJIXzldv3Y%2Bbhp6zThEllaKk%3D&expires=1611037476177',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: 'oWpEWMD6',
    name: '试一下页面是否可以选择出来',
    creator: 'zhangxueqi',
    creatorId: 'oNGzxQgB',
    createdAt: '2020-12-30T05:30:03Z',
    updater: 'zhangxueqi',
    updaterId: 'oNGzxQgB',
    updatedAt: '2020-12-30T05:30:03Z',
    description: '',
    platforms: ['iOS'],
    docType: 'page',
    actions: ['page'],
    patternMatched: false,
    attrs: {
      content: null,
      index: null,
      href: null,
      path: '/UITabBarController/UINavigationController[1]/GIOUICategoryViewController[0]',
      pg: null,
      query: null,
      xpath: null,
      contentType: null,
      domain: 'GrowingIO.GrowingIOTest-1221',
      urlScheme: 'growing.2c3914401a232d99',
      __typename: 'DocProps',
    },
    definition: {
      domain: 'GrowingIO.GrowingIOTest-1221',
      path: '/UITabBarController/UINavigationController[1]/GIOUICategoryViewController[0]',
      query: null,
      xpath: null,
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: 'growing.2c3914401a232d99',
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/0b44b1ca-a56d-4b70-8cac-aa0cb8637426.jpg?sign=KOqGPXgot5uWPrmyIQI3QFDs3gi0UuG%2Bwv8XmSpH9d0%3D&expires=1611037476177',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: 'NxDLLND7',
    name: '现在定义的是页面 pages/form/form 。',
    creator: 'lvyuqiang',
    creatorId: 'n1QVaDyR',
    createdAt: '2020-12-30T02:45:34Z',
    updater: 'mayutong',
    updaterId: 'nxGK0Da6',
    updatedAt: '2021-01-05T05:22:40Z',
    description:
      '现在定义的是页面 pages/form/form 。\n现在定义的是页面 pages/form/form 。\n现在定义的是页面 pages/form/form 。\n现在定义的是页面 pages/form/form 。\n现在定义的是页面 pages/form/form 。\n现在定义的是页面 pages/',
    platforms: ['minp'],
    docType: 'page',
    actions: ['page'],
    patternMatched: false,
    attrs: {
      content: null,
      index: null,
      href: null,
      path: 'pages/form/form',
      pg: null,
      query: null,
      xpath: null,
      contentType: null,
      domain: 'wx265d0fa6fa70fae9',
      urlScheme: null,
      __typename: 'DocProps',
    },
    definition: {
      domain: 'wx265d0fa6fa70fae9',
      path: 'pages/form/form',
      query: null,
      xpath: null,
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: null,
      __typename: 'DocProps',
    },
    screenshot: { target: '', viewport: '', __typename: 'Screenshot' },
    __typename: 'Element',
  },
  {
    id: 'nKD1BPQW',
    name: '小程序点击事件',
    creator: 'lvyuqiang',
    creatorId: 'n1QVaDyR',
    createdAt: '2020-12-29T11:45:32Z',
    updater: 'lvyuqiang',
    updaterId: 'n1QVaDyR',
    updatedAt: '2020-12-29T11:45:32Z',
    description: '',
    platforms: ['minp'],
    docType: 'elem',
    actions: ['clck'],
    patternMatched: false,
    attrs: {
      content: 'Web',
      index: '2',
      href: 'pages/h5/h5',
      path: 'pages/h5/h5',
      pg: null,
      query: null,
      xpath: '#onTabItemTap',
      contentType: null,
      domain: 'wx265d0fa6fa70fae9',
      urlScheme: null,
      __typename: 'DocProps',
    },
    definition: {
      domain: 'wx265d0fa6fa70fae9',
      path: 'pages/h5/h5',
      query: null,
      xpath: '#onTabItemTap',
      index: '2',
      href: 'pages/h5/h5',
      content: 'Web',
      pg: null,
      contentType: '=',
      urlScheme: null,
      __typename: 'DocProps',
    },
    screenshot: { target: '', viewport: '', __typename: 'Screenshot' },
    __typename: 'Element',
  },
  {
    id: 'JnG44mGz',
    name: '测试一组同类元素吧',
    creator: 'zhangxueqi',
    creatorId: 'oNGzxQgB',
    createdAt: '2020-12-28T07:48:02Z',
    updater: 'zhangxueqi',
    updaterId: 'oNGzxQgB',
    updatedAt: '2020-12-28T07:48:02Z',
    description: '',
    platforms: ['iOS'],
    docType: 'elem',
    actions: ['clck'],
    patternMatched: false,
    attrs: {
      content: null,
      index: '0',
      href: null,
      path: '/UITabBarController/UINavigationController[0]/MeasurementProtocolTableViewController[0]',
      pg: null,
      query: null,
      xpath: '/Page/Section[0]/UITableViewCell[-]',
      contentType: null,
      domain: 'GrowingIO.GrowingIOTest-1221',
      urlScheme: 'growing.2c3914401a232d99',
      __typename: 'DocProps',
    },
    definition: {
      domain: 'GrowingIO.GrowingIOTest-1221',
      path: '/UITabBarController/UINavigationController[0]/MeasurementProtocolTableViewController[0]',
      query: null,
      xpath: '/Page/Section[0]/UITableViewCell[-]',
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: 'growing.2c3914401a232d99',
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/9cdfa364-fc57-417f-9cd3-236bc254db6e.jpg?sign=8Pdf4HZlZvIA1jr2%2BTdjV%2Bem13jMbxOAgzjIR2LGroA%3D&expires=1611037476177',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: 'zZDbbKD9',
    name: '9785号选手',
    creator: 'zhangxueqi',
    creatorId: 'oNGzxQgB',
    createdAt: '2020-12-28T07:30:07Z',
    updater: 'zhangxueqi',
    updaterId: 'oNGzxQgB',
    updatedAt: '2020-12-28T07:30:07Z',
    description: '',
    platforms: ['iOS'],
    docType: 'page',
    actions: ['page'],
    patternMatched: false,
    attrs: {
      content: null,
      index: null,
      href: null,
      path: '/UITabBarController/UINavigationController[1]',
      pg: null,
      query: null,
      xpath: null,
      contentType: null,
      domain: 'GrowingIO.GrowingIOTest-1221',
      urlScheme: 'growing.2c3914401a232d99',
      __typename: 'DocProps',
    },
    definition: {
      domain: 'GrowingIO.GrowingIOTest-1221',
      path: '/UITabBarController/UINavigationController[1]',
      query: null,
      xpath: null,
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: 'growing.2c3914401a232d99',
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/5af1a836-cc94-47e0-919b-7c55cae64a85.jpg?sign=7MbusqAsfKYa8KGKl2KZlM0fNIHfKpg5Ze%2B3jI5wRD0%3D&expires=1611037476177',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: 'rRGoyYQm',
    name: 'test_原生页3面',
    creator: 'chenjianzhong',
    creatorId: 'evp9kDOx',
    createdAt: '2020-12-25T00:47:36Z',
    updater: 'chenjianzhong',
    updaterId: 'evp9kDOx',
    updatedAt: '2020-12-25T01:11:10Z',
    description: '',
    platforms: ['iOS'],
    docType: 'page',
    actions: ['page'],
    patternMatched: false,
    attrs: {
      content: null,
      index: null,
      href: null,
      path: '/UITabBarController/UINavigationController[0]/GIOCustomEventViewController[0]',
      pg: null,
      query: null,
      xpath: null,
      contentType: null,
      domain: 'GrowingIO.GrowingIOTest-1221',
      urlScheme: 'growing.2c3914401a232d99',
      __typename: 'DocProps',
    },
    definition: {
      domain: 'GrowingIO.GrowingIOTest-1221',
      path: '/UITabBarController/UINavigationController[0]/GIOCustomEventViewController[0]',
      query: null,
      xpath: null,
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: 'growing.2c3914401a232d99',
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/e63d6a4e-0c06-4f83-97b6-39ff87d55b47.jpg?sign=zb4NiAcu%2FsODM%2BDNffULV4UX%2FAxXHuFFqV0Uq9bXuMs%3D&expires=1611037476177',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: 'n1QVqaDy',
    name: '3333_click',
    creator: 'chenjianzhong',
    creatorId: 'evp9kDOx',
    createdAt: '2020-12-25T00:40:17Z',
    updater: 'chenjianzhong',
    updaterId: 'evp9kDOx',
    updatedAt: '2020-12-25T00:40:17Z',
    description: '',
    platforms: ['iOS'],
    docType: 'elem',
    actions: ['clck'],
    patternMatched: false,
    attrs: {
      content: null,
      index: '2',
      href: null,
      path: '/UITabBarController/UINavigationController[0]/MeasurementProtocolTableViewController[0]',
      pg: null,
      query: null,
      xpath: '/Page/Section[0]/UITableViewCell[-]',
      contentType: null,
      domain: 'GrowingIO.GrowingIOTest-1221',
      urlScheme: 'growing.2c3914401a232d99',
      __typename: 'DocProps',
    },
    definition: {
      domain: 'GrowingIO.GrowingIOTest-1221',
      path: '/UITabBarController/UINavigationController[0]/MeasurementProtocolTableViewController[0]',
      query: null,
      xpath: '/Page/Section[0]/UITableViewCell[-]',
      index: '2',
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: 'growing.2c3914401a232d99',
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/966e6cd3-05e3-450b-8c42-029916133a82.jpg?sign=eFZo3UJHx7t3yCIXcBmxrh8zoRthhLwODsefUqSiLYo%3D&expires=1611037476178',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: 'y9pmz1Gm',
    name: '2222',
    creator: 'chenjianzhong',
    creatorId: 'evp9kDOx',
    createdAt: '2020-12-25T00:39:35Z',
    updater: 'chenjianzhong',
    updaterId: 'evp9kDOx',
    updatedAt: '2020-12-25T00:39:35Z',
    description: '',
    platforms: ['iOS'],
    docType: 'page',
    actions: ['page'],
    patternMatched: false,
    attrs: {
      content: null,
      index: null,
      href: null,
      path: '/UITabBarController/UINavigationController[0]',
      pg: null,
      query: null,
      xpath: null,
      contentType: null,
      domain: 'GrowingIO.GrowingIOTest-1221',
      urlScheme: 'growing.2c3914401a232d99',
      __typename: 'DocProps',
    },
    definition: {
      domain: 'GrowingIO.GrowingIOTest-1221',
      path: '/UITabBarController/UINavigationController[0]',
      query: null,
      xpath: null,
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: 'growing.2c3914401a232d99',
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/c6121659-3d02-4363-9b63-507f538ce638.jpg?sign=5MTeDOn88FCu2EtBAFf0aS4wPmhe5zOtsYdOCe5WJlw%3D&expires=1611037476178',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: 'meQ8xQn3',
    name: '保存一下',
    creator: 'lvyuqiang',
    creatorId: 'n1QVaDyR',
    createdAt: '2020-12-21T06:28:33Z',
    updater: 'mayutong',
    updaterId: 'nxGK0Da6',
    updatedAt: '2021-01-06T06:59:27Z',
    description: 'dd',
    platforms: ['iOS'],
    docType: 'elem',
    actions: ['clck'],
    patternMatched: false,
    attrs: {
      content: null,
      index: '3',
      href: null,
      path: '/UITabBarController/UINavigationController[0]/MeasurementProtocolTableViewController[0]',
      pg: null,
      query: null,
      xpath: '/Page/Section[0]/UITableViewCell[-]',
      contentType: null,
      domain: 'GrowingIO.GrowingIOTest-',
      urlScheme: 'growing.2c3914401a232d99',
      __typename: 'DocProps',
    },
    definition: {
      domain: 'GrowingIO.GrowingIOTest-',
      path: '/UITabBarController/UINavigationController[0]/MeasurementProtocolTableViewController[0]',
      query: null,
      xpath: '/Page/Section[0]/UITableViewCell[-]',
      index: '3',
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: 'growing.2c3914401a232d99',
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/bb0647c5-5368-4563-bf7d-cdcc7e72f77c.jpg?sign=L0GjDAevM4t9DhmWTUbr5WtQuHqcMNOdYBJc5806ejE%3D&expires=1611037476177',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: '9yGOxDlk',
    name: '弹出页面',
    creator: 'lvyuqiang',
    creatorId: 'n1QVaDyR',
    createdAt: '2020-12-21T04:32:08Z',
    updater: 'lvyuqiang',
    updaterId: 'n1QVaDyR',
    updatedAt: '2020-12-21T04:32:08Z',
    description: '弹出页面',
    platforms: ['iOS'],
    docType: 'page',
    actions: ['page'],
    patternMatched: false,
    attrs: {
      content: null,
      index: null,
      href: null,
      path: '/UINavigationController/UIViewController[0]',
      pg: null,
      query: null,
      xpath: null,
      contentType: null,
      domain: 'GrowingIO.GrowingIOTest-',
      urlScheme: 'growing.2c3914401a232d99',
      __typename: 'DocProps',
    },
    definition: {
      domain: 'GrowingIO.GrowingIOTest-',
      path: '/UINavigationController/UIViewController[0]',
      query: null,
      xpath: null,
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: 'growing.2c3914401a232d99',
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/7b8e7dc7-9bd7-47e1-950b-d4419bf5c656.jpg?sign=k%2BzuX6vc78nuMLe3topI9LM5r4O0eobc9YTGT0RtXe8%3D&expires=1611037476178',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: 'kAGP4GRM',
    name: '1217ios定义元素之page请求',
    creator: 'mayutong',
    creatorId: 'nxGK0Da6',
    createdAt: '2020-12-17T11:54:14Z',
    updater: 'mayutong',
    updaterId: 'nxGK0Da6',
    updatedAt: '2020-12-17T11:54:14Z',
    description:
      '我是一段很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长很长的描述。。。',
    platforms: ['iOS'],
    docType: 'elem',
    actions: ['clck'],
    patternMatched: false,
    attrs: {
      content: null,
      index: '0',
      href: null,
      path: '/UITabBarController/UINavigationController[0]/MeasurementProtocolTableViewController[0]',
      pg: null,
      query: null,
      xpath: '/Page/Section[0]/UITableViewCell[-]',
      contentType: null,
      domain: 'GrowingIO.GrowingIOTest-1226',
      urlScheme: 'growing.447120b8e608d6b9',
      __typename: 'DocProps',
    },
    definition: {
      domain: 'GrowingIO.GrowingIOTest-1226',
      path: '/UITabBarController/UINavigationController[0]/MeasurementProtocolTableViewController[0]',
      query: null,
      xpath: '/Page/Section[0]/UITableViewCell[-]',
      index: '0',
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: 'growing.447120b8e608d6b9',
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/54ebf950-a8f6-4b3f-b5bf-3c8c1888618c.jpg?sign=XU0TQIHMpXj%2Bl1LhJDXuOzy1wsMPS0SyoEqPgPGMTrU%3D&expires=1611037476178',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: 'JMQ7bDm1',
    name: '定义页面啊',
    creator: 'mayutong',
    creatorId: 'nxGK0Da6',
    createdAt: '2020-12-17T11:53:47Z',
    updater: 'mayutong',
    updaterId: 'nxGK0Da6',
    updatedAt: '2020-12-17T11:53:47Z',
    description: '',
    platforms: ['iOS'],
    docType: 'page',
    actions: ['page'],
    patternMatched: false,
    attrs: {
      content: null,
      index: null,
      href: null,
      path: '/UITabBarController/UINavigationController[0]/MeasurementProtocolTableViewController[0]',
      pg: null,
      query: null,
      xpath: null,
      contentType: null,
      domain: 'GrowingIO.GrowingIOTest-1226',
      urlScheme: 'growing.447120b8e608d6b9',
      __typename: 'DocProps',
    },
    definition: {
      domain: 'GrowingIO.GrowingIOTest-1226',
      path: '/UITabBarController/UINavigationController[0]/MeasurementProtocolTableViewController[0]',
      query: null,
      xpath: null,
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: 'growing.447120b8e608d6b9',
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/a5aeacf3-44d6-4539-8a52-f0c1225d90b1.jpg?sign=f5Wl7N6%2BFoBz%2FsH3xEIePy2bjpnEr77K0a2WJK0XZuA%3D&expires=1611037476178',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: 'KnGnkDRY',
    name: '1217ios定义页面',
    creator: 'mayutong',
    creatorId: 'nxGK0Da6',
    createdAt: '2020-12-17T11:49:29Z',
    updater: 'mayutong',
    updaterId: 'nxGK0Da6',
    updatedAt: '2020-12-17T11:49:29Z',
    description: 'lalalalalalala',
    platforms: ['iOS'],
    docType: 'page',
    actions: ['page'],
    patternMatched: false,
    attrs: {
      content: null,
      index: null,
      href: null,
      path: '/UITabBarController',
      pg: null,
      query: null,
      xpath: null,
      contentType: null,
      domain: 'GrowingIO.GrowingIOTest-1226',
      urlScheme: 'growing.447120b8e608d6b9',
      __typename: 'DocProps',
    },
    definition: {
      domain: 'GrowingIO.GrowingIOTest-1226',
      path: '/UITabBarController',
      query: null,
      xpath: null,
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: 'growing.447120b8e608d6b9',
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/1169d1bc-e039-4cb7-ac12-51e435dd32b5.jpg?sign=Dg6%2BFO%2BVOP2exd1PFq%2B2Y11X5hQdTcyEYCt6VLgveEE%3D&expires=1611037476178',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: 'yJQA7G17',
    name: '/push/cdp/jdhybird.html',
    creator: 'lvyuqiang',
    creatorId: 'n1QVaDyR',
    createdAt: '2020-12-17T03:26:00Z',
    updater: 'lvyuqiang',
    updaterId: 'n1QVaDyR',
    updatedAt: '2020-12-17T03:26:00Z',
    description: '',
    platforms: ['iOS'],
    docType: 'page',
    actions: ['page'],
    patternMatched: false,
    attrs: {
      content: null,
      index: null,
      href: null,
      path: '/push/cdp/jdhybird.html',
      pg: null,
      query: null,
      xpath: null,
      contentType: null,
      domain: 'release-messages.growingio.cn',
      urlScheme: 'growing.2c3914401a232d99',
      __typename: 'DocProps',
    },
    definition: {
      domain: 'release-messages.growingio.cn',
      path: '/push/cdp/jdhybird.html',
      query: null,
      xpath: null,
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: 'growing.2c3914401a232d99',
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/3a3af67e-122a-44fc-af60-de49f19f4ab0.jpg?sign=5Mht5yufEpoB3Fxg81yQPIYQE8LHIpBJR9u1VHSVjic%3D&expires=1611037476178',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: 'weDqmDEX',
    name: '定义原生页面',
    creator: 'mayutong',
    creatorId: 'nxGK0Da6',
    createdAt: '2020-12-16T02:53:35Z',
    updater: 'mayutong',
    updaterId: 'nxGK0Da6',
    updatedAt: '2020-12-16T02:53:35Z',
    description: 'test',
    platforms: ['iOS'],
    docType: 'page',
    actions: ['page'],
    patternMatched: false,
    attrs: {
      content: null,
      index: null,
      href: null,
      path: '/UITabBarController/UINavigationController[1]',
      pg: null,
      query: null,
      xpath: null,
      contentType: null,
      domain: 'GrowingIO.GrowingIOTest-',
      urlScheme: 'growing.2c3914401a232d99',
      __typename: 'DocProps',
    },
    definition: {
      domain: 'GrowingIO.GrowingIOTest-',
      path: '/UITabBarController/UINavigationController[1]',
      query: null,
      xpath: null,
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: 'growing.2c3914401a232d99',
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/e07af990-77c7-4aa6-9afe-9182bc477509.jpg?sign=GcF5JXzkIqrbgcXhd3IiZUczo6wPdMGJYX4iYxWZm54%3D&expires=1611037476178',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: 'NxDLNp7E',
    name: 'dgg',
    creator: 'mayutong',
    creatorId: 'nxGK0Da6',
    createdAt: '2020-12-15T07:54:51Z',
    updater: 'mayutong',
    updaterId: 'nxGK0Da6',
    updatedAt: '2020-12-15T07:54:51Z',
    description: '',
    platforms: ['Android'],
    docType: 'elem',
    actions: ['clck'],
    patternMatched: false,
    attrs: {
      content: '清除账号',
      index: null,
      href: null,
      path: '/TrackActivity',
      pg: null,
      query: null,
      xpath: '/Page/ActionBarOverlayLayout[0]/FrameLayout[0]/LinearLayout[0]/Button[1]#btn_clean_userId',
      contentType: null,
      domain: 'com.growingio.android.cdp',
      urlScheme: 'growing.447120b8e608d6b9',
      __typename: 'DocProps',
    },
    definition: {
      domain: 'com.growingio.android.cdp',
      path: '/TrackActivity',
      query: null,
      xpath: '/Page/ActionBarOverlayLayout[0]/FrameLayout[0]/LinearLayout[0]/Button[1]#btn_clean_userId',
      index: null,
      href: null,
      content: '清除账号',
      pg: null,
      contentType: '=',
      urlScheme: 'growing.447120b8e608d6b9',
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/d40340d6-b64e-423b-b9b4-55db7afb1a5c.jpg?sign=%2BULB4UGLkaFbzEhh09l4Bs5vXCD8KMP8NKRFhL%2BJTxM%3D&expires=1611037476178',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: 'nKD1PGWr',
    name: '877687687',
    creator: 'mayutong',
    creatorId: 'nxGK0Da6',
    createdAt: '2020-12-15T07:54:33Z',
    updater: 'mayutong',
    updaterId: 'nxGK0Da6',
    updatedAt: '2020-12-15T07:54:33Z',
    description: '',
    platforms: ['Android'],
    docType: 'elem',
    actions: ['clck'],
    patternMatched: false,
    attrs: {
      content: '设置账号李四',
      index: null,
      href: null,
      path: '/TrackActivity',
      pg: null,
      query: null,
      xpath: '/Page/ActionBarOverlayLayout[0]/FrameLayout[0]/LinearLayout[0]/Button[2]#btn_set_user_lisi',
      contentType: null,
      domain: 'com.growingio.android.cdp',
      urlScheme: 'growing.447120b8e608d6b9',
      __typename: 'DocProps',
    },
    definition: {
      domain: 'com.growingio.android.cdp',
      path: '/TrackActivity',
      query: null,
      xpath: '/Page/ActionBarOverlayLayout[0]/FrameLayout[0]/LinearLayout[0]/Button[2]#btn_set_user_lisi',
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: 'growing.447120b8e608d6b9',
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/9d896c9e-d371-465c-9477-16a5ca35b343.jpg?sign=YbWb4eTexlkPnxopNT8DX1DrrzUH%2Fsx%2FYuHwA%2Ft8Izc%3D&expires=1611037476178',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: 'qyD6qGKJ',
    name: '列表第三位',
    creator: 'mayutong',
    creatorId: 'nxGK0Da6',
    createdAt: '2020-12-15T07:50:49Z',
    updater: 'mayutong',
    updaterId: 'nxGK0Da6',
    updatedAt: '2020-12-15T07:50:49Z',
    description: '',
    platforms: ['Android'],
    docType: 'elem',
    actions: ['clck'],
    patternMatched: false,
    attrs: {
      content: '设置账号李四',
      index: null,
      href: null,
      path: '/TrackActivity',
      pg: null,
      query: null,
      xpath: '/Page/ActionBarOverlayLayout[0]/FrameLayout[0]/LinearLayout[0]/Button[2]#btn_set_user_lisi',
      contentType: null,
      domain: 'com.growingio.android.cdp',
      urlScheme: 'growing.447120b8e608d6b9',
      __typename: 'DocProps',
    },
    definition: {
      domain: 'com.growingio.android.cdp',
      path: '/TrackActivity',
      query: null,
      xpath: '/Page/ActionBarOverlayLayout[0]/FrameLayout[0]/LinearLayout[0]/Button[2]#btn_set_user_lisi',
      index: null,
      href: null,
      content: '设置账号李四',
      pg: null,
      contentType: '=',
      urlScheme: 'growing.447120b8e608d6b9',
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/2b785149-9064-4d42-96e5-06a82d94b1a4.jpg?sign=GVs9HokUI%2BC%2BTN2wHp3bGsj0WUnb3Er339pVhYRg6pU%3D&expires=1611037476178',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: 'xNQXjGMb',
    name: 'autotracker-cdp页面',
    creator: 'mayutong',
    creatorId: 'nxGK0Da6',
    createdAt: '2020-12-15T07:50:07Z',
    updater: 'mayutong',
    updaterId: 'nxGK0Da6',
    updatedAt: '2020-12-15T07:50:07Z',
    description: '',
    platforms: ['Android'],
    docType: 'page',
    actions: ['page'],
    patternMatched: false,
    attrs: {
      content: null,
      index: null,
      href: null,
      path: '/TrackActivity',
      pg: null,
      query: null,
      xpath: null,
      contentType: null,
      domain: 'com.growingio.android.cdp',
      urlScheme: 'growing.447120b8e608d6b9',
      __typename: 'DocProps',
    },
    definition: {
      domain: 'com.growingio.android.cdp',
      path: '/TrackActivity',
      query: null,
      xpath: null,
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: 'growing.447120b8e608d6b9',
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/2740844b-cb23-4868-8a43-d0f5cd150cc8.jpg?sign=LV5Clhvs36wRzmvx83nGR9J76ZvqDFp%2F1D54C7PixOs%3D&expires=1611037476178',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: '3mpxwQOq',
    name: '现在定义的是 所属页面 中，当前位置 ，限定 元素内容包含「',
    creator: 'lvyuqiang',
    creatorId: 'n1QVaDyR',
    createdAt: '2020-12-15T03:16:12Z',
    updater: 'lvyuqiang',
    updaterId: 'n1QVaDyR',
    updatedAt: '2020-12-15T03:16:12Z',
    description:
      '现在定义的是 所属页面 中，当前位置 ，限定 元素内容包含「ChangeUserId」的元素。若元素的内容改变，就不再继续统计了。\n',
    platforms: ['iOS'],
    docType: 'elem',
    actions: ['clck'],
    patternMatched: false,
    attrs: {
      content: 'ChangeUserId',
      index: null,
      href: null,
      path: '/UITabBarController/UINavigationController[0]/GIOUserIdViewController[0]',
      pg: null,
      query: null,
      xpath: '/Page/UIView/UIButton[1]',
      contentType: null,
      domain: 'GrowingIO.GrowingIOTest-',
      urlScheme: 'growing.2c3914401a232d99',
      __typename: 'DocProps',
    },
    definition: {
      domain: 'GrowingIO.GrowingIOTest-',
      path: '/UITabBarController/UINavigationController[0]/GIOUserIdViewController[0]',
      query: null,
      xpath: '/Page/UIView/UIButton[1]',
      index: null,
      href: null,
      content: 'ChangeUserId',
      pg: null,
      contentType: 'match_phrase',
      urlScheme: 'growing.2c3914401a232d99',
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/be5b952d-3ca6-4b4d-8288-aa3151a85fe0.jpg?sign=PrQPUcBO8ppXj%2BFUehQ%2BbYUAaPsR1X2rtJLrrOe3eFI%3D&expires=1611037476178',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: 'qVDgrGkw',
    name: '现在定义的是页面 /UITabBarController/U',
    creator: 'lvyuqiang',
    creatorId: 'n1QVaDyR',
    createdAt: '2020-12-15T03:15:39Z',
    updater: 'lvyuqiang',
    updaterId: 'n1QVaDyR',
    updatedAt: '2020-12-15T03:15:39Z',
    description: '现在定义的是页面 /UITabBarController/UINavigationController[0]/GIOUserIdViewController[0] 。',
    platforms: ['iOS'],
    docType: 'page',
    actions: ['page'],
    patternMatched: false,
    attrs: {
      content: null,
      index: null,
      href: null,
      path: '/UITabBarController/UINavigationController[0]/GIOUserIdViewController[0]',
      pg: null,
      query: null,
      xpath: null,
      contentType: null,
      domain: 'GrowingIO.GrowingIOTest-',
      urlScheme: 'growing.2c3914401a232d99',
      __typename: 'DocProps',
    },
    definition: {
      domain: 'GrowingIO.GrowingIOTest-',
      path: '/UITabBarController/UINavigationController[0]/GIOUserIdViewController[0]',
      query: null,
      xpath: null,
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: 'growing.2c3914401a232d99',
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/023d40b6-231a-4bac-a6f7-1a1cd8aa4336.jpg?sign=KrylATsgiiLE%2FqgBr8gGzRatR%2FOkacWs787wGnx1k1k%3D&expires=1611037476178',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: 'mgGJLQA4',
    name: 'test_YUANSU',
    creator: 'mayutong',
    creatorId: 'nxGK0Da6',
    createdAt: '2020-12-14T09:53:54Z',
    updater: 'mayutong',
    updaterId: 'nxGK0Da6',
    updatedAt: '2020-12-14T09:57:31Z',
    description: '33',
    platforms: ['Android'],
    docType: 'elem',
    actions: ['clck'],
    patternMatched: false,
    attrs: {
      content: '一共测试4种数据类型, change, click, submit, page,',
      index: null,
      href: null,
      path: '/push/cdp/testgio-cdpcircel.html',
      pg: null,
      query: null,
      xpath: '/div.title/form.basic-grey/h1/span',
      contentType: null,
      domain: 'release-messages.growingio.cn',
      urlScheme: 'growing.447120b8e608d6b9',
      __typename: 'DocProps',
    },
    definition: {
      domain: 'release-messages.growingio.cn',
      path: '/push/cdp/testgio-cdpcircel.html',
      query: null,
      xpath: '/div.title/form.basic-grey/h1/span',
      index: null,
      href: null,
      content: '一共测试4种数据类型, change, click, submit, page,',
      pg: null,
      contentType: '=',
      urlScheme: 'growing.447120b8e608d6b9',
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/34d130eb-2536-4d36-a596-932616f2edde.jpg?sign=Fbd%2BK16Uzmxf1uSUflks4z2Pi9XRkK54oO9Aj4CH3ME%3D&expires=1611037476178',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: 'WkDyOpe4',
    name: '现在定义的是页面 /MainActivity 。',
    creator: 'lvyuqiang',
    creatorId: 'n1QVaDyR',
    createdAt: '2020-12-14T09:18:43Z',
    updater: 'lvyuqiang',
    updaterId: 'n1QVaDyR',
    updatedAt: '2020-12-14T09:18:43Z',
    description: '现在定义的是页面 /MainActivity 。',
    platforms: ['Android'],
    docType: 'page',
    actions: ['page'],
    patternMatched: false,
    attrs: {
      content: null,
      index: null,
      href: null,
      path: '/MainActivity',
      pg: null,
      query: null,
      xpath: null,
      contentType: null,
      domain: 'com.growingio.android.cdp',
      urlScheme: 'growing.447120b8e608d6b9',
      __typename: 'DocProps',
    },
    definition: {
      domain: 'com.growingio.android.cdp',
      path: '/MainActivity',
      query: null,
      xpath: null,
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: 'growing.447120b8e608d6b9',
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/fa32d131-8c91-4fdf-80e8-44884e5e00b5.jpg?sign=gi2etLcLCazJTfRAKWA3OnNGbT4H5v4wpoQ3BdwpsSk%3D&expires=1611037476178',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
];
export const deviceInfoMinp = { name: '小程序无埋点', domain: 'wx265d0fa6fa70fae9', os: 'minp' };
export const currentPageMinp = {
  id: 'f339fcb2bdd07fd7b55020c2835d8bede823e4af',
  eventType: 'PAGE',
  timestamp: 1610954652616,
  ip: '111.198.136.131',
  domain: 'wx265d0fa6fa70fae9',
  query: 'name=hello&a=3',
  platform: 'MinP',
  path: 'pages/index/index',
  appType: 0,
  actions: ['clck'],
};
