export const spaceTags = [
  {
    id: 'JnG40OGz',
    name: '是',
    creator: 'haozhigang',
    creatorId: 'rRGoYQml',
    createdAt: '2021-01-14T07:08:25Z',
    updater: 'haozhigang',
    updaterId: 'rRGoYQml',
    updatedAt: '2021-01-14T07:08:25Z',
    description: '是  得到的',
    platforms: ['minp'],
    docType: 'page',
    actions: ['page'],
    patternMatched: false,
    attrs: {
      content: null,
      index: null,
      href: null,
      path: 'pages/index/index',
      pg: null,
      query: null,
      xpath: null,
      contentType: null,
      domain: 'wx123456',
      urlScheme: null,
      __typename: 'DocProps',
    },
    definition: {
      domain: 'wx123456',
      path: 'pages/index/index',
      query: '得到的=s',
      xpath: null,
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: null,
      __typename: 'DocProps',
    },
    screenshot: { target: '', viewport: '', __typename: 'Screenshot' },
    __typename: 'Element',
  },
];
export const deviceInfoMinp = { name: '小程序无埋点', domain: 'wx123456', os: 'minp' };
export const currentPageMinp = {
  id: 'f339fcb2bdd07fd7b55020c2835d8bede823e4af',
  eventType: 'PAGE',
  timestamp: 1610954652616,
  ip: '111.198.136.131',
  domain: 'wx123456',
  query: 'name=hello&a=3',
  platform: 'MinP',
  path: 'pages/index/index',
  appType: 0,
  actions: ['clck'],
};
export const deviceInfoApp = {
  projectId: '91eaf9b283361032',
  msgType: 'ready',
  timestamp: 1612755238635,
  domain: 'com.growingio.android.cdp',
  sdkVersion: '3.0.0',
  sdkVersionCode: 30000,
  os: 'Android',
  screenWidth: 1080,
  screenHeight: 1920,
  urlScheme: 'growing.314b5db864634231',
  name: 'Android无埋点测试',
};
export const currentPageApp = {
  path: '/MainActivity',
  title: 'AutoTracker-CDP',
  left: 0,
  top: 0,
  width: 343.125,
  height: 610,
  isIgnored: false,
  appType: 1,
  domain: 'com.growingio.android.cdp',
  isDefined: false,
  tags: [],
};
export const definedTags2 = [
  {
    id: 'wWDrnvDM',
    name: 'safdgfhh',
    creator: '郝志刚',
    creatorId: '9yGOLaDl',
    createdAt: '2021-02-07T11:14:41Z',
    updater: '郝志刚',
    updaterId: '9yGOLaDl',
    updatedAt: '2021-02-07T11:14:41Z',
    description: 'sdfgf',
    platforms: ['Android'],
    docType: 'elem',
    actions: ['clck'],
    patternMatched: false,
    attrs: {
      content: 'autotest',
      index: null,
      href: null,
      path: '/push/cdp/testgio-cdpcircel.html',
      pg: null,
      query: null,
      xpath: '/div.main/div.title/h2',
      contentType: null,
      domain: 'release-messages.growingio.cn',
      urlScheme: 'growing.314b5db864634231',
      __typename: 'DocProps',
    },
    definition: {
      domain: 'release-messages.growingio.cn',
      path: '/push/cdp/testgio-cdpcircel.html',
      query: null,
      xpath: '/div.main/div.title/h2',
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: '=',
      urlScheme: 'growing.314b5db864634231',
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/a6e0223a-721f-4a10-8566-3eb770eae184.jpg?sign=%2BVnwIBaZtcLwsExIbPGYK0bsYMlPjsfRqM4bGkk8AdQ%3D&expires=1612838000711',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: 'NxDLPLD7',
    name: '定义带跳转链接的元素3',
    creator: '马雨彤',
    creatorId: 'evp9bjGO',
    createdAt: '2021-02-06T10:19:40Z',
    updater: '马雨彤',
    updaterId: 'evp9bjGO',
    updatedAt: '2021-02-06T10:19:40Z',
    description: '两个限定条件：只勾选内容，模糊匹配\n',
    platforms: ['Android'],
    docType: 'elem',
    actions: ['clck'],
    patternMatched: false,
    attrs: {
      content: '点我跳转本地页面 test.html',
      index: null,
      href: './test.html',
      path: '/push/cdp/testgio-cdpcircel.html',
      pg: null,
      query: null,
      xpath: '/div.main/div.title/form.basic-grey/a',
      contentType: null,
      domain: 'release-messages.growingio.cn',
      urlScheme: 'growing.314b5db864634231',
      __typename: 'DocProps',
    },
    definition: {
      domain: 'release-messages.growingio.cn',
      path: '/push/cdp/testgio-cdpcircel.html',
      query: null,
      xpath: '/div.main/div.title/form.basic-grey/a',
      index: null,
      href: './test.html',
      content: '点我跳转本地页面 test.html',
      pg: null,
      contentType: 'match_phrase',
      urlScheme: 'growing.314b5db864634231',
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/ad121ed6-dd19-4a9b-8d09-ff2e1694ca5e.jpg?sign=1vFQxGtlRT%2B7bqg2WfFE31S35ii1AY7QTsIgiEFyh%2BQ%3D&expires=1612838000712',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: 'nKD1OvpW',
    name: '定义带跳转链接的元素2',
    creator: '马雨彤',
    creatorId: 'evp9bjGO',
    createdAt: '2021-02-06T10:18:54Z',
    updater: '马雨彤',
    updaterId: 'evp9bjGO',
    updatedAt: '2021-02-06T10:18:54Z',
    description: '两个限定条件：只勾选内容且精准匹配',
    platforms: ['Android'],
    docType: 'elem',
    actions: ['clck'],
    patternMatched: false,
    attrs: {
      content: '点我跳转本地页面 test.html',
      index: null,
      href: './test.html',
      path: '/push/cdp/testgio-cdpcircel.html',
      pg: null,
      query: null,
      xpath: '/div.main/div.title/form.basic-grey/a',
      contentType: null,
      domain: 'release-messages.growingio.cn',
      urlScheme: 'growing.314b5db864634231',
      __typename: 'DocProps',
    },
    definition: {
      domain: 'release-messages.growingio.cn',
      path: '/push/cdp/testgio-cdpcircel.html',
      query: null,
      xpath: '/div.main/div.title/form.basic-grey/a',
      index: null,
      href: './test.html',
      content: '点我跳转本地页面 test.html xxx',
      pg: null,
      contentType: '=',
      urlScheme: 'growing.314b5db864634231',
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/fd70a335-ccbc-4870-a357-4f990bea56b9.jpg?sign=fzGXN3tDPBZeG7NWkg3hjhNv3kIQBb3H%2FeDKG%2BcI23A%3D&expires=1612838000712',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: 'qyD6ezGK',
    name: '定义带跳转链接的元素',
    creator: '马雨彤',
    creatorId: 'evp9bjGO',
    createdAt: '2021-02-06T10:14:51Z',
    updater: '马雨彤',
    updaterId: 'evp9bjGO',
    updatedAt: '2021-02-06T10:14:51Z',
    description: '两个限定条件：内容和链接都选择。',
    platforms: ['Android'],
    docType: 'elem',
    actions: ['clck'],
    patternMatched: false,
    attrs: {
      content: '点我跳转本地页面 test.html',
      index: null,
      href: './test.html',
      path: '/push/cdp/testgio-cdpcircel.html',
      pg: null,
      query: null,
      xpath: '/div.main/div.title/form.basic-grey/a',
      contentType: null,
      domain: 'release-messages.growingio.cn',
      urlScheme: 'growing.314b5db864634231',
      __typename: 'DocProps',
    },
    definition: {
      domain: 'release-messages.growingio.cn',
      path: '/push/cdp/testgio-cdpcircel.html',
      query: 'c=3',
      xpath: '/div.main/div.title/form.basic-grey/a',
      index: null,
      href: './test.html',
      content: '点我跳转本地页面 test.html',
      pg: null,
      contentType: '=',
      urlScheme: 'growing.314b5db864634231',
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/feecbfac-b6ae-4c09-ae99-25330aa7ea05.jpg?sign=iE9FKrVssrA8r0yuBbPFN44BXRv%2F4FBfacLj53F117s%3D&expires=1612838000712',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: 'xNQXXZQM',
    name: '定义输入框',
    creator: '马雨彤',
    creatorId: 'evp9bjGO',
    createdAt: '2021-02-06T10:12:27Z',
    updater: '马雨彤',
    updaterId: 'evp9bjGO',
    updatedAt: '2021-02-06T10:12:27Z',
    description: '无限定条件',
    platforms: ['Android'],
    docType: 'elem',
    actions: ['clck'],
    patternMatched: false,
    attrs: {
      content: null,
      index: null,
      href: null,
      path: '/push/cdp/testgio-cdpcircel.html',
      pg: null,
      query: null,
      xpath: '/div.title/form.basic-grey/label/input#name.name',
      contentType: null,
      domain: 'release-messages.growingio.cn',
      urlScheme: 'growing.314b5db864634231',
      __typename: 'DocProps',
    },
    definition: {
      domain: 'release-messages.growingio.cn',
      path: '/push/cdp/testgio-cdpcircel.html',
      query: null,
      xpath: '/div.title/form.basic-grey/label/input#name.name',
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: 'growing.314b5db864634231',
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/80109d31-2cac-4fbb-924e-c01191bfc753.jpg?sign=nZ0AK62Kc4v5Xvn%2FUTJkNFUpNE7Y31UJAvawsWrL%2FBw%3D&expires=1612838000712',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: '0wDaMAD1',
    name: '定义元素',
    creator: '马雨彤',
    creatorId: 'evp9bjGO',
    createdAt: '2021-02-06T10:00:08Z',
    updater: '马雨彤',
    updaterId: 'evp9bjGO',
    updatedAt: '2021-02-06T10:00:08Z',
    description: '勾选元素内容',
    platforms: ['Android'],
    docType: 'elem',
    actions: ['clck'],
    patternMatched: false,
    attrs: {
      content: 'autotest',
      index: null,
      href: null,
      path: '/push/cdp/testgio-cdpcircel.html',
      pg: null,
      query: null,
      xpath: '/div.main/div.title/h2',
      contentType: null,
      domain: 'release-messages.growingio.cn',
      urlScheme: 'growing.314b5db864634231',
      __typename: 'DocProps',
    },
    definition: {
      domain: 'release-messages.growingio.cn',
      path: '/push/cdp/testgio-cdpcircel.html',
      query: 'c=3',
      xpath: '/div.main/div.title/h2',
      index: null,
      href: null,
      content: 'autotest',
      pg: null,
      contentType: '=',
      urlScheme: 'growing.314b5db864634231',
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/3eed8730-ddd0-4a53-94e7-88a43f2cdd93.jpg?sign=BXsDm9eEkW%2FaMgCX6Miuh5BcStaaoFQjlI1nqBdSThM%3D&expires=1612838000712',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: '3mpxlvpO',
    name: '定义元素时定义一个新页面',
    creator: '马雨彤',
    creatorId: 'evp9bjGO',
    createdAt: '2021-02-06T09:59:35Z',
    updater: '马雨彤',
    updaterId: 'evp9bjGO',
    updatedAt: '2021-02-06T09:59:35Z',
    description: '',
    platforms: ['Android'],
    docType: 'page',
    actions: ['page'],
    patternMatched: false,
    attrs: {
      content: null,
      index: null,
      href: null,
      path: '/push/cdp/testgio-cdpcircel.html',
      pg: null,
      query: null,
      xpath: null,
      contentType: null,
      domain: 'release-messages.growingio.cn',
      urlScheme: 'growing.314b5db864634231',
      __typename: 'DocProps',
    },
    definition: {
      domain: 'release-messages.growingio.cn',
      path: '/push/cdp/testgio-cdpcircel.html',
      query: 'c=3',
      xpath: null,
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: 'growing.314b5db864634231',
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/d05e4576-2408-4c9b-a482-683423634c33.jpg?sign=wlPX%2FTXjxHaGD2Hljzy6h310Wx%2Ff%2F0JNFJgOTl1%2FYwc%3D&expires=1612838000712',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: 'qVDgz8Gk',
    name: '定义H5路径关闭有多个查询条件',
    creator: '马雨彤',
    creatorId: 'evp9bjGO',
    createdAt: '2021-02-06T09:58:39Z',
    updater: '马雨彤',
    updaterId: 'evp9bjGO',
    updatedAt: '2021-02-06T09:58:39Z',
    description: '',
    platforms: ['Android'],
    docType: 'page',
    actions: ['page'],
    patternMatched: false,
    attrs: {
      content: null,
      index: null,
      href: null,
      path: '/push/cdp/testgio-cdpcircel.html',
      pg: null,
      query: null,
      xpath: null,
      contentType: null,
      domain: 'release-messages.growingio.cn',
      urlScheme: 'growing.314b5db864634231',
      __typename: 'DocProps',
    },
    definition: {
      domain: 'release-messages.growingio.cn',
      path: '/push/cdp/testgio-cdpcircel.html',
      query: 'a=1&b=2',
      xpath: null,
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: 'growing.314b5db864634231',
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/acb5d472-0e9a-4afd-9f32-abbbcb891142.jpg?sign=OMX9qt8lIbSHO5c6PYD50IOAwbW1MyMwE%2Bwhhuwcf6Y%3D&expires=1612838000712',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: 'qgQMqVQ3',
    name: '定义H5路径关闭有1个查询条件',
    creator: '马雨彤',
    creatorId: 'evp9bjGO',
    createdAt: '2021-02-06T09:57:55Z',
    updater: '马雨彤',
    updaterId: 'evp9bjGO',
    updatedAt: '2021-02-06T09:57:55Z',
    description: '路径有值。',
    platforms: ['Android'],
    docType: 'page',
    actions: ['page'],
    patternMatched: false,
    attrs: {
      content: null,
      index: null,
      href: null,
      path: '/push/cdp/testgio-cdpcircel.html',
      pg: null,
      query: null,
      xpath: null,
      contentType: null,
      domain: 'release-messages.growingio.cn',
      urlScheme: 'growing.314b5db864634231',
      __typename: 'DocProps',
    },
    definition: {
      domain: 'release-messages.growingio.cn',
      path: '/push/cdp/testgio-cdpcircel.html',
      query: 'a=1',
      xpath: null,
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: 'growing.314b5db864634231',
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/e407eef3-2075-4f19-9538-6efdaa279a1a.jpg?sign=H%2BycktdviScj7LdMN5RNZ6PQYfriMRirZEfgHAwvYbA%3D&expires=1612838000712',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: 'OqQjM7Dd',
    name: '定义H5路径打开不为空有多个查询条件',
    creator: '马雨彤',
    creatorId: 'evp9bjGO',
    createdAt: '2021-02-06T09:54:19Z',
    updater: '马雨彤',
    updaterId: 'evp9bjGO',
    updatedAt: '2021-02-06T09:54:19Z',
    description: '',
    platforms: ['Android'],
    docType: 'page',
    actions: ['page'],
    patternMatched: false,
    attrs: {
      content: null,
      index: null,
      href: null,
      path: '/push/cdp/testgio-cdpcircel.html',
      pg: null,
      query: null,
      xpath: null,
      contentType: null,
      domain: 'release-messages.growingio.cn',
      urlScheme: 'growing.314b5db864634231',
      __typename: 'DocProps',
    },
    definition: {
      domain: 'release-messages.growingio.cn',
      path: '/pages/index',
      query: 'a=1&b=2',
      xpath: null,
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: 'growing.314b5db864634231',
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/561ff474-5d01-4d8f-b658-426163e3d66e.jpg?sign=azrjPEYcbgIT%2Flo4tKnW4%2BVTl4a%2BEPyJSEpyludPH1I%3D&expires=1612838000712',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: 'V0G5XgpA',
    name: '定义H5路径打开不为空有1个查询条件',
    creator: '马雨彤',
    creatorId: 'evp9bjGO',
    createdAt: '2021-02-06T09:50:24Z',
    updater: '马雨彤',
    updaterId: 'evp9bjGO',
    updatedAt: '2021-02-06T09:50:24Z',
    description: '',
    platforms: ['Android'],
    docType: 'page',
    actions: ['page'],
    patternMatched: false,
    attrs: {
      content: null,
      index: null,
      href: null,
      path: '/push/cdp/testgio-cdpcircel.html',
      pg: null,
      query: null,
      xpath: null,
      contentType: null,
      domain: 'release-messages.growingio.cn',
      urlScheme: 'growing.314b5db864634231',
      __typename: 'DocProps',
    },
    definition: {
      domain: 'release-messages.growingio.cn',
      path: '/pages/index',
      query: 'a=1',
      xpath: null,
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: 'growing.314b5db864634231',
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/8540d973-4398-4c37-ba24-0c8f429bbca2.jpg?sign=zxwSgBBk35QIIZENSpTEIrPYFfVQTf711okyEEwxs30%3D&expires=1612838000712',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: 'oNGzm2pg',
    name: '定义H5路径打开不为空无查询条件',
    creator: '马雨彤',
    creatorId: 'evp9bjGO',
    createdAt: '2021-02-06T09:45:38Z',
    updater: '马雨彤',
    updaterId: 'evp9bjGO',
    updatedAt: '2021-02-06T09:45:38Z',
    description: '！！！',
    platforms: ['Android'],
    docType: 'page',
    actions: ['page'],
    patternMatched: false,
    attrs: {
      content: null,
      index: null,
      href: null,
      path: '/push/cdp/testgio-cdpcircel.html',
      pg: null,
      query: null,
      xpath: null,
      contentType: null,
      domain: 'release-messages.growingio.cn',
      urlScheme: 'growing.314b5db864634231',
      __typename: 'DocProps',
    },
    definition: {
      domain: 'release-messages.growingio.cn',
      path: '/pages',
      query: null,
      xpath: null,
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: 'growing.314b5db864634231',
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/f866de35-324e-4d26-9ebf-f21fefb392ae.jpg?sign=10sHSDX9MD1l658co9JtsoHUERwvbBbgOBG75nvRJVU%3D&expires=1612838000712',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
  {
    id: 'KzpNB5pk',
    name: '尝试定义H5页面！',
    creator: '马雨彤',
    creatorId: 'evp9bjGO',
    createdAt: '2021-02-06T09:39:34Z',
    updater: '马雨彤',
    updaterId: 'evp9bjGO',
    updatedAt: '2021-02-06T09:39:34Z',
    description: '希望可以成功叭！',
    platforms: ['Android'],
    docType: 'page',
    actions: ['page'],
    patternMatched: false,
    attrs: {
      content: null,
      index: null,
      href: null,
      path: '/push/cdp/testgio-cdpcircel.html',
      pg: null,
      query: null,
      xpath: null,
      contentType: null,
      domain: 'release-messages.growingio.cn',
      urlScheme: 'growing.314b5db864634231',
      __typename: 'DocProps',
    },
    definition: {
      domain: 'release-messages.growingio.cn',
      path: '/push/cdp/testgio-cdpcircel.html',
      query: null,
      xpath: null,
      index: null,
      href: null,
      content: null,
      pg: null,
      contentType: null,
      urlScheme: 'growing.314b5db864634231',
      __typename: 'DocProps',
    },
    screenshot: {
      target: '',
      viewport:
        '/screenshots-uploads/screenshots/656c1896-f9c0-4ed4-b6ec-8e45b4621a45.jpg?sign=4igh1sreJsx1I0QUGQjg3%2FU6h5H1%2FsCHL6OTcYsLG8s%3D&expires=1612838000712',
      __typename: 'Screenshot',
    },
    __typename: 'Element',
  },
];
