import { definedPages } from './pagePicker.data';
// eslint-disable-next-line import/prefer-default-export
export const elements: any = {
  element1: {
    name: 'element1',
    content: 'element1:一共测试4种数据类型, change, click, submit, page,',
    index: '1',
    href: '/link',
    path: 'pages/index/index',
    pg: null,
    query: '',
    xpath: '/div.title/form.basic-grey/h1/span',
    contentType: null,
    domain: 'wx123456',
    urlScheme: 'growing.447120b8e608d6b9',
    actions: ['clck'],
  },
  element2: {
    name: 'element2',
    content: '测试',
    path: 'pages/form/form',
    pg: null,
    query: 'a=1',
    xpath: '/div.title/form.basic-grey/h1/span',
    contentType: null,
    domain: 'wx123456',
    urlScheme: 'growing.447120b8e608d6b9',
    actions: ['clck'],
  },
  element3: {
    name: 'element3',
    content: '测试',
    path: 'pages/form/form',
    pg: null,
    query: null,
    xpath: '/div.title/form.basic-grey/h1/span',
    contentType: null,
    domain: 'release-messages.growingio.cn',
    urlScheme: 'growing.447120b8e608d6b9',
    actions: ['clck'],
  },
  element4: {
    name: 'element4',
    content: 'element2:这是2',
    path: 'pages/form/form',
    pg: null,
    query: null,
    xpath: '/div.title/form.basic-grey/h1/span',
    contentType: null,
    domain: 'release-messages.growingio.cn',
    urlScheme: 'growing.447120b8e608d6b9',
    actions: ['clck'],
  },
};

export const definedElements: any = [
  ...definedPages,
  {
    name: 'element1',
    description: '',
    docType: 'elem',
    actions: ['clck'],
    attrs: {
      domain: 'wx123456',
      path: 'pages/index/index',
      query: '',
      xpath: '/div.title/form.basic-grey/h1/span',
      index: '',
      href: '',
      content: 'element1:一共测试4种数据类型, change, click, submit, page,',
    },
    definition: {
      domain: 'wx123456',
      path: 'pages/index/index',
      query: null,
      xpath: '/div.title/form.basic-grey/h1/span',
      index: '1',
      href: '/link',
      content: 'element1:一共测试4种数据类型, change, click, submit, page,',
      contentType: '=',
    },
    platforms: ['minp'],
  },
  {
    name: 'element11',
    description: '',
    belongApp: '小程序无埋点 | wx123456',
    docType: 'elem',
    actions: ['clck'],
    platforms: ['web'],
    attrs: {
      domain: 'wx123456',
      path: 'pages/index/index',
      query: '',
      xpath: '/div.title/form.basic-grey/h1/span',
      index: '',
      href: '',
      content: 'element1:一共测试4种数据类型, change, click, submit, page,',
    },
    definition: {
      domain: 'wx123456',
      path: 'pages/index/index',
      query: null,
      xpath: '/div.title/form.basic-grey/h1/span',
      index: '1',
      href: '/link',
      content: 'element1:一共测试4种数据类型, change, click, submit, page,',
      contentType: '=',
    },
  },
  {
    name: 'element1',
    description: '',
    docType: 'elem',
    actions: ['clck'],
    attrs: {
      domain: 'wx123456',
      path: 'pages/index/index',
      query: '',
      xpath: '/div.title/form.basic-grey/h1/span',
      index: '',
      href: '',
      content: 'element1:一共测试4种数据类型, change, click, submit, page,',
      urlScheme: 'growing.314b5db864634231',
    },
    definition: {
      domain: 'wx123456',
      path: 'pages/index/index',
      query: null,
      xpath: '/div.title/form.basic-grey/h1/span',
      index: '1',
      href: '/link',
      content: 'element1:一共测试4种数据类型, change, click, submit, page,',
      urlScheme: 'growing.314b5db864634231',
      contentType: '=',
    },
    platforms: ['android'],
  },
];
