export const complex = {
  id: 'kqQewGry',
  name: '功能留存率',
  type: 'complex',
  action: '',
  elementId: '',
  valueType: '',
  platforms: ['all'],
  favorites: false,
  isComplexDistinct: true,
  __typename: 'Measurable',
  selectKey: 'complex-kqQewGry',
  groups: ['unknown'],
};
export const simple = {
  id: 'WkDy3Npe',
  name: '定义新页面',
  type: 'simple',
  action: 'page',
  elementId: 'oWpE8eQ6',
  valueType: '',
  platforms: ['minp'],
  favorites: false,
  isComplexDistinct: false,
  __typename: 'Measurable',
  selectKey: 'simple-WkDy3Npe',
  groups: ['unknown'],
};
export const custom = {
  id: 'meQ8JnGn',
  name: '埋点事件1',
  type: 'custom',
  action: '',
  elementId: '',
  valueType: 'counter',
  platforms: ['all'],
  favorites: false,
  attributes: [
    { id: '9yGOKaGl', name: 'test_1210_string', valueType: 'string', __typename: 'MeasurableAttribute' },
    { id: 'kAGP21QR', name: 'test_1210_int', valueType: 'int', __typename: 'MeasurableAttribute' },
    { id: 'yJQA8yD1', name: 'test_1210_double', valueType: 'double', __typename: 'MeasurableAttribute' },
  ],
  isComplexDistinct: false,
  __typename: 'Measurable',
  selectKey: 'custom-meQ8JnGn',
  groups: ['unknown'],
};
export const custom2 = {
  id: 'meQ8JnGn',
  name: '埋点事件1',
  type: 'custom',
  action: '',
  elementId: '',
  valueType: 'counter',
  platforms: ['all'],
  favorites: false,
  // attributes: [
  //   { id: '9yGOKaGl', name: 'test_1210_string', valueType: 'string', __typename: 'MeasurableAttribute' },
  //   { id: 'kAGP21QR', name: 'test_1210_int', valueType: 'int', __typename: 'MeasurableAttribute' },
  //   { id: 'yJQA8yD1', name: 'test_1210_double', valueType: 'double', __typename: 'MeasurableAttribute' },
  // ],
  itemModels: [
    { id: '9yGOKaGl', name: 'test_1210_string', valueType: 'string', __typename: 'MeasurableAttribute' },
    { id: 'kAGP21QR', name: 'test_1210_int', valueType: 'int', __typename: 'MeasurableAttribute' },
    { id: 'yJQA8yD1', name: 'test_1210_double', valueType: 'double', __typename: 'MeasurableAttribute' },
  ],
  isComplexDistinct: false,
  __typename: 'Measurable',
  selectKey: 'custom-meQ8JnGn',
  groups: ['unknown'],
};
export const prepared = {
  id: 'uc',
  name: '用户量---对网站、App、小程序有过访问的独立用户数量',
  description: '对网站、App、小程序有过访问的独立用户数量',
  instruction: '',
  platforms: ['all'],
  __typename: 'PreparedMetric',
  selectKey: '-uc',
  groups: ['prepared'],
  type: 'prepared',
};
