// eslint-disable-next-line import/prefer-default-export
export const events = [
  {
    id: 'yJQA7G17',
    name: '/push/cdp/jdhybird.html',
    type: 'simple',
    action: 'page',
    elementId: 'yJQA7G17',
    valueType: '',
    platforms: ['iOS'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'bVG2Ap68',
    name: '0319-test地方',
    type: 'complex',
    action: '',
    elementId: '',
    valueType: '',
    platforms: ['all'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'WkDyn8Qe',
    name: '1',
    type: 'simple',
    action: 'page',
    elementId: 'KzpNq5Qk',
    valueType: '',
    platforms: ['minp'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'KnGnkDRY',
    name: '1217ios定义页面',
    type: 'simple',
    action: 'page',
    elementId: 'KnGnkDRY',
    valueType: '',
    platforms: ['iOS'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'kAGP4GRM',
    name: '1217ios定义元素之page请求',
    type: 'simple',
    action: 'clck',
    elementId: 'kAGP4GRM',
    valueType: '',
    platforms: ['iOS'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'evp9MEpO',
    name: '1月13，21次',
    type: 'simple',
    action: 'page',
    elementId: 'zZDb6aD9',
    valueType: '',
    platforms: ['minp'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'y9pmz1Gm',
    name: '2222',
    type: 'simple',
    action: 'page',
    elementId: 'y9pmz1Gm',
    valueType: '',
    platforms: ['iOS'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'n1QVqaDy',
    name: '3333_click',
    type: 'simple',
    action: 'clck',
    elementId: 'n1QVqaDy',
    valueType: '',
    platforms: ['iOS'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'zqQR3po3',
    name: '44',
    type: 'complex',
    action: '',
    elementId: '',
    valueType: '',
    platforms: ['all'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'y9pm5Wpm',
    name: '8',
    type: 'simple',
    action: 'page',
    elementId: 'zqQRv5Qo',
    valueType: '',
    platforms: ['web'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'nKD1PGWr',
    name: '877687687',
    type: 'simple',
    action: 'clck',
    elementId: 'nKD1PGWr',
    valueType: '',
    platforms: ['Android'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'zZDbbKD9',
    name: '9785号选手',
    type: 'simple',
    action: 'page',
    elementId: 'zZDbbKD9',
    valueType: '',
    platforms: ['iOS'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'meQ8xQn3',
    name: '保存一下',
    type: 'simple',
    action: 'clck',
    elementId: 'meQ8xQn3',
    valueType: '',
    platforms: ['iOS'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: '9yGOMxQl',
    name: '测试页面 主',
    type: 'simple',
    action: 'page',
    elementId: 'J1GlMEDj',
    valueType: '',
    platforms: ['iOS'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'JnG44mGz',
    name: '测试一组同类元素吧',
    type: 'simple',
    action: 'clck',
    elementId: 'JnG44mGz',
    valueType: '',
    platforms: ['iOS'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: '9yGOxDlk',
    name: '弹出页面',
    type: 'simple',
    action: 'page',
    elementId: '9yGOxDlk',
    valueType: '',
    platforms: ['iOS'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'J1GlMVDj',
    name: '点我按钮',
    type: 'simple',
    action: 'clck',
    elementId: 'rRGoj8pm',
    valueType: '',
    platforms: ['web'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'oNGzm2pg',
    name: '定义页面',
    type: 'simple',
    action: 'page',
    elementId: 'NxDLPLD7',
    valueType: '',
    platforms: ['web'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'JMQ7bDm1',
    name: '定义页面啊',
    type: 'simple',
    action: 'page',
    elementId: 'JMQ7bDm1',
    valueType: '',
    platforms: ['iOS'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'zqQR25Qo',
    name: '定义一个新的事件2',
    type: 'simple',
    action: 'clck',
    elementId: 'kqQe1qQr',
    valueType: '',
    platforms: ['minp'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'weDqmDEX',
    name: '定义原生页面',
    type: 'simple',
    action: 'page',
    elementId: 'weDqmDEX',
    valueType: '',
    platforms: ['iOS'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'y9pm1Wpm',
    name: '加一份奶盖',
    type: 'simple',
    action: 'clck',
    elementId: 'wWDrjvDM',
    valueType: '',
    platforms: ['minp'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'bVG24AQ6',
    name: '柯基图片按钮',
    type: 'simple',
    action: 'clck',
    elementId: 'AbQ343pY',
    valueType: '',
    platforms: ['web'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'qyD6qGKJ',
    name: '列表第三位',
    type: 'simple',
    action: 'clck',
    elementId: 'qyD6qGKJ',
    valueType: '',
    platforms: ['Android'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'ExQWkOQ7',
    name: '设置用户属性',
    type: 'simple',
    action: 'clck',
    elementId: 'n1QVdoGy',
    valueType: '',
    platforms: ['web'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'RqQww9QJ',
    name: '是',
    type: 'simple',
    action: 'page',
    elementId: 'JnG40OGz',
    valueType: '',
    platforms: ['minp'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'AbQ343pY',
    name: '事件1',
    type: 'simple',
    action: 'clck',
    elementId: 'zqQR25Qo',
    valueType: '',
    platforms: ['minp'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'wWDrjvDM',
    name: '事件2的页面',
    type: 'simple',
    action: 'page',
    elementId: '7RDYqYDA',
    valueType: '',
    platforms: ['minp'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'klGvBYG7',
    name: '事件4',
    type: 'simple',
    action: 'page',
    elementId: 'ExQWkgQ7',
    valueType: '',
    platforms: ['minp'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'qyD6aqGK',
    name: '试一下页面是否可以选择出来',
    type: 'simple',
    action: 'page',
    elementId: 'oWpEWMD6',
    valueType: '',
    platforms: ['iOS'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'mgGJy2pA',
    name: '我',
    type: 'simple',
    action: 'clck',
    elementId: 'V0G5MgGA',
    valueType: '',
    platforms: ['Android'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'nKD1BPQW',
    name: '想要测试一下选择页面的交互',
    type: 'simple',
    action: 'page',
    elementId: 'MvDB8VpO',
    valueType: '',
    platforms: ['iOS'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: '3mpxwQOq',
    name: '现在定义的是 所属页面 中，当前位置 ，限定 元素内容包含「',
    type: 'simple',
    action: 'clck',
    elementId: '3mpxwQOq',
    valueType: '',
    platforms: ['iOS'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'WkDyOpe4',
    name: '现在定义的是页面 /MainActivity 。',
    type: 'simple',
    action: 'page',
    elementId: 'WkDyOpe4',
    valueType: '',
    platforms: ['Android'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'qVDgrGkw',
    name: '现在定义的是页面 /UITabBarController/U',
    type: 'simple',
    action: 'page',
    elementId: 'qVDgrGkw',
    valueType: '',
    platforms: ['iOS'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'xNQXmjpM',
    name: '现在定义的是页面 pages/form/form 。',
    type: 'simple',
    action: 'page',
    elementId: 'NxDLLND7',
    valueType: '',
    platforms: ['minp'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'o8D0M3Q7',
    name: '小程序点击事件',
    type: 'simple',
    action: 'clck',
    elementId: 'nKD1BPQW',
    valueType: '',
    platforms: ['minp'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'WlGkXLDa',
    name: '整站页面',
    type: 'simple',
    action: 'page',
    elementId: 'klGvBYG7',
    valueType: '',
    platforms: ['web'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'AbQ3b3DY',
    name: 'aaa',
    type: 'simple',
    action: 'page',
    elementId: 'nxGKqxQa',
    valueType: '',
    platforms: ['web'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'zZDbAaG9',
    name: 'aaafjuasdaiosfjioas',
    type: 'simple',
    action: 'clck',
    elementId: 'xNQXXZQM',
    valueType: '',
    platforms: ['web'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'xNQXjGMb',
    name: 'autotracker-cdp页面',
    type: 'simple',
    action: 'page',
    elementId: 'xNQXjGMb',
    valueType: '',
    platforms: ['Android'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'V0G5XgpA',
    name: 'ccccc',
    type: 'simple',
    action: 'clck',
    elementId: 'oWpEl6Q6',
    valueType: '',
    platforms: ['web'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'ExQWOQ79',
    name: 'custom_event_name',
    type: 'custom',
    action: '',
    elementId: '',
    valueType: 'number',
    platforms: ['all'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'zqQR3po3',
    name: 'dataCenter_getInsightDimensions',
    type: 'custom',
    action: '',
    elementId: '',
    valueType: 'counter',
    platforms: ['all'],
    labels: [],
    favorites: false,
    attributes: [
      {
        id: 'rRGoYQml',
        name: 'dataCenter_getInsightDimensions',
        valueType: 'string',
        __typename: 'MeasurableAttribute',
      },
    ],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: '7RDYeDA8',
    name: 'dataCenter_searchCustomEventKeys',
    type: 'custom',
    action: '',
    elementId: '',
    valueType: 'number',
    platforms: ['all'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'zZDb6aD9',
    name: 'dfgh',
    type: 'simple',
    action: 'clck',
    elementId: 'OqQjw7pd',
    valueType: '',
    platforms: ['Android'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'NxDLNp7E',
    name: 'dgg',
    type: 'simple',
    action: 'clck',
    elementId: 'NxDLNp7E',
    valueType: '',
    platforms: ['Android'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'WlGk4Daj',
    name: 'eweq',
    type: 'complex',
    action: '',
    elementId: '',
    valueType: '',
    platforms: ['all'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'nxGK0Da6',
    name: 'getInsightDimensions',
    type: 'custom',
    action: '',
    elementId: '',
    valueType: 'counter',
    platforms: ['all'],
    labels: [],
    favorites: false,
    attributes: [
      { id: 'klGvyp7E', name: 'getInsightDimensions', valueType: 'string', __typename: 'MeasurableAttribute' },
    ],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'mgGJE2pA',
    name: 'hghjfghggfgh',
    type: 'simple',
    action: 'clck',
    elementId: '0wDaMAD1',
    valueType: '',
    platforms: ['web'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'klGvyp7E',
    name: 'iostest',
    type: 'custom',
    action: '',
    elementId: '',
    valueType: 'counter',
    platforms: ['all'],
    labels: [],
    favorites: false,
    attributes: [{ id: 'WlGk4Daj', name: 'ok', valueType: 'string', __typename: 'MeasurableAttribute' }],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'rRGoYQml',
    name: 'iostest01',
    type: 'custom',
    action: '',
    elementId: '',
    valueType: 'counter',
    platforms: ['all'],
    labels: [],
    favorites: false,
    attributes: [{ id: 'y9pm1pme', name: '范若若f', valueType: 'string', __typename: 'MeasurableAttribute' }],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'JnG4nOQz',
    name: 'liudan-test',
    type: 'simple',
    action: 'clck',
    elementId: 'qyD6ezGK',
    valueType: '',
    platforms: ['web'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'ExQWkgQ7',
    name: 'ls-jk',
    type: 'simple',
    action: 'clck',
    elementId: 'WkDyn8Qe',
    valueType: '',
    platforms: ['web'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: '7RDYqYDA',
    name: 'ls-xl',
    type: 'simple',
    action: 'chng',
    elementId: 'AVpZWyGK',
    valueType: '',
    platforms: ['web'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'y9pm1pme',
    name: 'order',
    type: 'custom',
    action: '',
    elementId: '',
    valueType: 'counter',
    platforms: ['all'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'evp9kDOx',
    name: 'project_search_by_key',
    type: 'custom',
    action: '',
    elementId: '',
    valueType: 'counter',
    platforms: ['all'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'RqQwPpJw',
    name: 'project_search_by_name',
    type: 'custom',
    action: '',
    elementId: '',
    valueType: 'counter',
    platforms: ['all'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'AbQ3bDYe',
    name: 'resourceItemTest',
    type: 'custom',
    action: '',
    elementId: '',
    valueType: 'counter',
    platforms: ['all'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'kqQewGry',
    name: 'search_by_name',
    type: 'custom',
    action: '',
    elementId: '',
    valueType: 'number',
    platforms: ['all'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'n1QVaDyR',
    name: 'testEvent',
    type: 'custom',
    action: '',
    elementId: '',
    valueType: 'counter',
    platforms: ['all'],
    labels: [],
    favorites: false,
    attributes: [{ id: 'y9pm1pme', name: '范若若f', valueType: 'string', __typename: 'MeasurableAttribute' }],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'NxDLLND7',
    name: 'test小程序',
    type: 'simple',
    action: 'page',
    elementId: 'weDq7mpE',
    valueType: '',
    platforms: ['minp'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'mgGJLQA4',
    name: 'test_0319_1',
    type: 'custom',
    action: '',
    elementId: '',
    valueType: 'counter',
    platforms: ['all'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'y9pm11pm',
    name: 'test_测试新定义页面',
    type: 'simple',
    action: 'page',
    elementId: 'rRGojYpm',
    valueType: '',
    platforms: ['minp'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'oWpEWMD6',
    name: 'test_所属页面小程序',
    type: 'simple',
    action: 'page',
    elementId: 'yJQA67p1',
    valueType: '',
    platforms: ['minp'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'rRGoyYQm',
    name: 'test_原生页3面',
    type: 'simple',
    action: 'page',
    elementId: 'rRGoyYQm',
    valueType: '',
    platforms: ['iOS'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'mgGJLQA4',
    name: 'test_YUANSU',
    type: 'simple',
    action: 'clck',
    elementId: 'mgGJLQA4',
    valueType: '',
    platforms: ['Android'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'MvDB8VpO',
    name: 'test_元素点击小程序',
    type: 'simple',
    action: 'clck',
    elementId: 'KnGnakpR',
    valueType: '',
    platforms: ['minp'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'wWDrwQML',
    name: 'test_getMeasurements',
    type: 'custom',
    action: '',
    elementId: '',
    valueType: 'counter',
    platforms: ['all'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'AVpZWyGK',
    name: 'w',
    type: 'simple',
    action: 'page',
    elementId: 'oNGzr2Gg',
    valueType: '',
    platforms: ['Android'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'kqQe1qQr',
    name: 'wx123 的是页面 pages/form/form 。',
    type: 'simple',
    action: 'page',
    elementId: 'mgGJy2pA',
    valueType: '',
    platforms: ['minp'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'JnG40OGz',
    name: 'xcvbn',
    type: 'simple',
    action: 'clck',
    elementId: 'qgQMkVG3',
    valueType: '',
    platforms: ['Android'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
  {
    id: 'KzpNB5pk',
    name: 'your email',
    type: 'simple',
    action: 'clck',
    elementId: 'nKD1OvpW',
    valueType: '',
    platforms: ['web'],
    labels: [],
    favorites: false,
    attributes: [],
    isComplexDistinct: false,
    __typename: 'Measurable',
  },
];
