name: Continuous Delivery
on:
  push:
    branches:
      - master
jobs:
  install:
    name: Install dependencies
    if: ${{ !(startsWith(github.event.head_commit.message, 'chore') || startsWith(github.event.head_commit.message, 'ci')) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - name: Cache Node.js modules
        id: cache-node-modules
        uses: actions/cache@v2.1.5
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Install
        if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
        run: yarn install
  lint:
    name: Lint codes
    needs: install
    if: ${{ !startsWith(github.event.head_commit.message, 'docs') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - name: Restore Node.js modules
        uses: actions/cache@v2.1.5
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: StyleLint
        run: yarn stylelint
      - name: ESLint
        run: yarn eslint
  unit_test:
    name: Unit test
    needs: install
    if: ${{ !startsWith(github.event.head_commit.message, 'docs') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - name: Restore Node.js modules
        uses: actions/cache@v2.1.5
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Test
        run: yarn test --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: coverage/
  build:
    name: Build package
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x
      - name: Restore Node.js modules
        uses: actions/cache@v2.1.5
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Cache package
        id: cache-package
        uses: actions/cache@v2.1.5
        with:
          path: |
            dist
            es
          key: package-${{ github.sha }}
      - name: Build package
        if: steps.cache-package.outputs.cache-hit != 'true'
        run: yarn build
  publish-package:
    name: Publish package
    needs: build
    if: ${{ startsWith(github.event.head_commit.message, 'docs(release)') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
      - name: Restore Node.js modules
        uses: actions/cache@v2.1.5
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Restore package from cache
        uses: actions/cache@v2.1.5
        with:
          path: |
            dist
            es
          key: package-${{ github.sha }}
      - name: Publish package
        run: yarn publish --non-interactive --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Get package version
        id: get-package-version
        run: echo "::set-output name=version::$(yarn -s get-version)"
      - name: Publish GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get-package-version.outputs.version }}
          release_name: v${{ steps.get-package-version.outputs.version }}
          body_path: VERSION.md
          draft: false
          prerelease: false
  publish-storybook:
    name: Publish storybook
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14
      - name: Restore Node.js modules
        uses: actions/cache@v2.1.5
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Build Storybook
        run: yarn build-storybook
      - name: Upload to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_TOKEN }}
          storybookBuildDir: storybook-static/
          exitZeroOnChanges: true
          exitOnceUploaded: true
          allowConsoleErrors: true
