name: Publishing Packages
on:
  release:
    types:
      - published
jobs:
  publish_npm:
    name: Publishing packages to the npm registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '1'
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x
          registry-url: 'https://registry.npmjs.org'
      - name: Restore packages from cache
        uses: actions/cache@v2
        with:
          path: |
            dist
            es
          key: packages-${{ github.sha }}
      - name: Publish from package
        run: yarn publish --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
